### ISSUE TITLE
jemalloc exhausts vma

### ISSUE THREAD

**Issue by dutor** [jemalloc/jemalloc#1011]
We have a multithreading server  which utilizes RocksDB. Once a while, the server crashed during the full compaction process, which is heavily memory consuming. The backtrace indicated that it was due to a huge(32MB) memory allocation failure. With further inspections on the lucky servers, we found that the number 
 of `vma` was nearly exhausted(63550 out of 65530).

So, here are the questions:
 * In what circumstances can a process occupy way more virtual memory spaces than it actually needs?
 * What's the best practice to avoid this issue, in terms of jemalloc's options and the memory usage pattern of the applications?
 * Besides increasing `vm.max_map_count`, are there any other workarounds to deal with this?

FYR. We use jemalloc 4.4.0, and Linux kernel is 3.10, on x86_64 platform.

Thanks!

**Comment by davidtgoldblatt** [comment]
The 4.4 release is a little before my time, but it sounds like you're hitting the issue fixed in #462 (that fact that you're hitting this in 4.4, with its chunk-based allocation, is impressive - out of curiosity, how large are your heaps?).

Upgrading to 5.0 should fix things for you, if that's possible.

> In what circumstances can a process occupy way more virtual memory spaces than it actually needs?

Address space fragmentation is a likely cause of this; even if we don't need the memory, we can't necessarily fill in space in the mappings.

> What's the best practice to avoid this issue, in terms of jemalloc's options and the memory usage pattern of the applications?

Switching to 5.0 should fix the issue entirely, I suspect. (5.0 has some other benefits as well, in terms of memory consumption and CPU usage, so this might help out otherwise too).

> Besides increasing vm.max_map_count, are there any other workarounds to deal with this?

I think the kernel knob is the easiest. If that and upgrading would be tricky, then I *think* setting "dss:primary" in your malloc_conf might help, but no promises (I suspect the kernel will merge sbrk'd mappings, but I can't claim to have actually tried it).

**Comment by dutor** [comment]
@davidtgoldblatt Thanks for the quick response.

> how large are your heaps?

As I have seen, before any compaction happened, `VIRT` and `RSS` from `top` are almost equal(~270GB). But after a compaction, `RSS` stays the same, if it survives, while `VIRT` being doubled to 550GB. 

> Address space fragmentation is a likely cause of this; even if we don't need the memory, we can't necessarily fill in space in the mappings.

I will adapt `vm.max_map_count` for a rescue for now and upgrade to 5.0 in the near future to see if it works.

Again, thank you!

**Comment by interwq** [comment]
Closing for now. Feel free to let us know if any questions.
