### ISSUE TITLE
will malloc and free in different thread  benifit from using jemalloc?

### ISSUE THREAD

**Issue by happyxgang** [jemalloc/jemalloc#1030]
We use a model that malloc and decode message in one thread, handle and free the message in another thread.
will we benefit from using jemalloc?

**Comment by davidtgoldblatt** [comment]
Yes, probably. Producer-consumer patterns are tricky to deal with because of the tendency to cause imbalances in thread-local caches, but the batching of moving objects into or out of those caches from the underlying allocator should improve performance relative to libc.

An easy way to test this would be to LD_PRELOAD libjemalloc.so when running your binary. This should get you results without having to substantially modify your build.

**Comment by davidtgoldblatt** [comment]
Closing for now, feel free to reopen if you have further questions.
