### ISSUE TITLE
What does "suitably aligned for storage of any type of object" mean?

### ISSUE THREAD

**Issue by SimonSapin** [jemalloc/jemalloc#1072]
http://jemalloc.net/jemalloc.3.html#description says:

> The `malloc()` function allocates `size` bytes of uninitialized memory. The allocated space is suitably aligned (after possible pointer coercion) for storage of any type of object.

What does this mean more precisely, about alignment? The Rust standard library currently assumes that the alignment is always at least 8 bytes on 32-bit platforms and 16 bytes on 64-bit platforms. But that appears to be incorrect, at least when `size` is less than that: https://github.com/rust-lang/rust/issues/45955

The C standard says `malloc()` alignment is at least `alignof(max_align_t)`, but only define that with a tautology as far as I could find. It is 16 in GCC and clang on my x86_64 laptop, though. https://gcc.gnu.org/ml/gcc-patches/2016-08/msg01902.html suggests that real-world allocators tend to ignore that part of the standard.

So, what alignment assumptions can Rust safely make when calling jemalloc’s `malloc()`?

----

By the way, this whole thing was added as a "micro-optimization" to call e.g. `calloc` over `mallocx` when the assumed minimum would already satisfy the requested alignment. Is there really any point in doing that?

**Comment by davidtgoldblatt** [comment]
I believe that your description of C's malloc alignment requirements is subtly incorrect; the returned pointer need not always be alignof(max_align_t) aligned, only aligned enough to store any object with an alignment <= max_align_t bytes that can occupy the returned storage. In particular, since size must be a multiple of alignment (because of the possibility of array access), no objects of size 8 have an alignment of 16 (for example, `sizeof(struct { char _Alignas(16) data; })` is 16).

You can force 16-byte alignment by configuring with `--with-lg-quantum=4`, if that helps.

I'm hesitant to commit to anything formal in terms of alignment, but sizes divisible by 2**N are currently aligned on a 2**N boundary for small N, and I don't think that will change any time soon. (You can see the size classes in include/jemalloc/internal/size_classes.h; all allocations are at an offset of a multiple of the size from a page).

As far as calloc vs. mallocx question, that should probably help slightly. Most of the allocation pathways share code, but we do some tricks to optimize out all the branches where possible. The fact that mallocx allows for more customization also means taking some extra branches and prevents some compiler optimizations.

**Comment by SimonSapin** [comment]
Thanks for the clarification. That makes sense. Does it sound correct to re-interpret it like this? “Given a requested alignment (a power of two) `align` and a requested size `size`, malloc() can satisfy that request if `align <= size && align <= alignof(max_align_t)`.”

(This is from the point of view of implementing the Rust standard library’s `Alloc::alloc` API which takes an arbitrary size and alignment as parameters. Though maybe a request with `align > size` doesn’t make sense in the first place and we’d be better off not allowing it.)

**Comment by davidtgoldblatt** [comment]
Not quite; that doesn't work for the case size == 24 and alignment == 16, which might only be 8-byte aligned. (Although, now that you have me thinking about it, I think that this handling of the 24 byte case may not be correct, because of the possibility of a trailing flexible array member, so that this is a jemalloc bug; I opened #1073 to discuss).

There are a few cases where align > size makes sense; suppose you want to embed a pointer to an int alongside 10 bits of metadata within a single word. Then you'd want to allocate a 4-byte object at a 1k alignment.

(Re-reading my earlier reply, I noticed it wasn't completely clear; the size of a *type* must be a multiple of its alignment; it's possible to have alignment requirements for storage for which this doesn't hold).

**Comment by SimonSapin** [comment]
Does something similar happen for size == 12 and alignment == 8, maybe on 32-bit platforms?

**Comment by davidtgoldblatt** [comment]
Yeah, that's 64-bit specific. I believe the same thing should happen there (though I don't remember the 32-bit size classes we'll pick off the top of my head).

**Comment by davidtgoldblatt** [comment]
Although, for your case, I don't believe Rust allows flexible array members in structs, so I don't think this should manifest if your fast-path checks use C alignment rules. (Not that I'm terribly familiar with Rust).

**Comment by davidtgoldblatt** [comment]
Update: the 24-byte size class does not in fact exist; we're correct as is unless the user opts-out (see #1073). (I'm dumb).

**Comment by davidtgoldblatt** [comment]
In that case, as for your proposed `align <= size && align <= alignof(max_align_t)`: I believe that this works.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/46117 has landed, doing that. Thanks for your feedback!
