### ISSUE TITLE
32-bit test failures with percpu arenas when purging is disabled

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#1105]
To reproduce:
```
CC="gcc -m32" CXX="g++ -m32" ./configure
make -j test/integration/mallocx
MALLOC_CONF=percpu_arena:percpu,dirty_decay_ms:-1,muzzy_decay_ms:-1 test/integration/mallocx
```

This bisects to fac706836ffda46759914508b918e8b54c8020c8 . It's not 100% reproducible, but it happens most of the time on my machine.

Broader question:
I feel like we're constantly breaking percpu arenas, and have mostly decided we think they're a bad idea (at least, until we've done some more thorough redesigns). Should we just kill them and be grateful that we have one less feature to maintain?

**Comment by davidtgoldblatt** [comment]
(feel free to bounce back if you don't have the time, I just figured you might have more of the right context on this one).

**Comment by interwq** [comment]
@davidtgoldblatt: I cannot repro this on my server, even looping many times. Can you try and see if it still happens for you?

**Comment by interwq** [comment]
It starts happening when I rebase to fac7068 directly. Is this the same error as you observed @davidtgoldblatt ?

test_alignment_and_size:test/integration/mallocx.c:181: Failed assertion: (ps[i]) != (NULL) --> 0x0 == 0x0: mallocx() error for alignment=4194304, size=12582907 (0xbffffb)
<jemalloc>: src/jemalloc.c:2879: Failed assertion: "ptr != NULL"

**Comment by davidtgoldblatt** [comment]
Yes, I think that's the one.

**Comment by interwq** [comment]
So `test_alignment_and_size` utilizes memory close to 4G, while fac7068 limits reusing dirty extents if the size gap is large, combined with percpu arena may using multiple arenas (instead of just 1 w/o percpu arena), it was pushed over the edge for 32bit. Coincidentally, ba5992f improved the fit for aligned allocations and it stopped happening after that. However to be safe, let's skip the test when percpu arena is enabled.
