### ISSUE TITLE
configure script?

### ISSUE THREAD

**Issue by markcurtis1970** [jemalloc/jemalloc#1191]
I cloned this repo just now and was following the install instructions but couldn't seem to find the `configure` script?

```
:~/jemalloc$ find . -name "*configure*"
./configure.ac
```

I suspect I'm having a bit of a brain fart but perhaps theres a reason this is not present?

**Comment by interwq** [comment]
Hi, if you get the source code from the repo, you'll want to do `./autogen.sh` as mentioned in https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md

**Comment by markcurtis1970** [comment]
Hi @interwq - thanks, but when I run that script I get the following error too:

```
$ ./autogen.sh
autoconf
./autogen.sh: 5: ./autogen.sh: autoconf: not found
```

**Comment by interwq** [comment]
@markcurtis1970: NP. This means you need to install autoconf on the system.

**Comment by antirez** [comment]
Hello @interwq,

Usually in order to embed the Jemalloc source code inside Redis, I always used to grab the packaged version of Jemalloc. Now it appears that it is no longer available, since the file I downloaded from Github under the "releases" section for Jemalloc 5.1.0 appears to be unpackaged. Of course I can run autogen, but I don't want Redis users to have autotools installed. So I wonder, what are the steps to create a packaged version of Jemalloc? Running autogen.sh is not enough since the git ignore file has all the files created in the ignore list, so I guess you have some shell script or alike to create a packaged version? Thanks. Moreover please note that generating the VERSION when Jemalloc is embedded inside another Git repository still fails, this bug is there for a few years, I wonder if there is interest in fixing it, AFAIK there are already PRs but I can otherwise try to fix it myself and provide a PR here. Thank you.

**Comment by jasone** [comment]
The packaged version is at
https://github.com/jemalloc/jemalloc/releases/download/5.1.0/jemalloc-5.1.0.tar.bz2 , linked in the Assets list at https://github.com/jemalloc/jemalloc/releases/tag/5.1.0 .  I just verified that the `configure` script is pre-generated.
