### ISSUE TITLE
VIRT exhausted running RocksDB

### ISSUE THREAD

**Issue by squalfof** [jemalloc/jemalloc#1198]
hi, i was running RocksDB v5.8.8 built with libjemalloc.a v5.0.1(all default settings), on Cent 6.7.
After some huge jobs, VIRT rises to 61G while RES remains as 13G. Seems VIRT acts the abnormal way.
Tried with tcmalloc, it works well under the same jobs.
I've collected some stats with the attachment. 
[jeprof.txt](https://github.com/jemalloc/jemalloc/files/1969630/jeprof.txt)

Really appreciate if any suggestions provided. Thanks.

**Comment by interwq** [comment]
Hi, the attached snapshot doesn't seem to show high VM usage (mapped + retained ~30G). Can you please check the stats when it's under high VIRT? 

On a related note, we are aware a VM fragmentation issue in 5.0.1. It was fixed in dev branch already. We are releasing 5.1 in a couple of days. So feel free to try the current dev branch to see if it fixes the issue.

**Comment by interwq** [comment]
Thanks for clarifying. Yes the second snapshot has higher VM. In fact the resident is very high (~22G) because of the # of dirty pages: `dirty:   N/A      3072088` means there are ~12G of memory stay cached. Be default jemalloc returns freed dirty memory to OS with a [time-based decay algorithm](http://jemalloc.net/jemalloc.3.html#opt.dirty_decay_ms). So memory will be kept in a while before returning back to kernel.

A few things to try:
1) try the current dev branch (which will be 5.1 release in a couple of days).
2) try adding `background_thread:true` to your config, e.g. via env var MALLOC_CONF=background_thread:true
3) if above 2 doesn't solve it for you, you may want to tune decay time. Check the guide here: https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md

Is virtual memory size a concern for you? We usually optimize for resident memory, and in our experience VM size being a few times of resident is fine (above options should help resident size more).

**Comment by squalfof** [comment]
Is virtual memory size a concern for you?
-- Yes, we use jemalloc v3.6 in production env, and it could use up to 370G VIRT while RES is 44G, for which some shell command like ``popen()`` could not be executed due to [overcommit-accounting issue](https://github.com/torvalds/linux/blob/master/Documentation/vm/overcommit-accounting). 

A few things to try:
-- Tried both ``background_thread:true`` and dev branch these days, still 60G VIRT compared with 14G RES, maybe it's the normal case, sadly shell commands could not be used this way. Thanks anyway.

**Comment by interwq** [comment]
If the goal and priority is to reduce VM usage, try using “retain:false”.

**Comment by squalfof** [comment]
Cool, it works, VIRT reduced as expected this time.

**Comment by interwq** [comment]
Keep in mind that with retain disabled you might be paying slightly higher CPU cost, depending on the workload.

**Comment by squalfof** [comment]
ah, will do some perf test on it 👍
