### ISSUE TITLE
jemalloc does not return back memory to kernel

### ISSUE THREAD

**Issue by pangqingyuan1991** [jemalloc/jemalloc#1230]
Here is my test code:
`int main(int argc, char *argv[])
    {
        void *ptr[1024];
        int i;
        for(i=0;i<1024;i++){
            ptr[i] = malloc(1024*1024);
            memset(ptr[i], 0 , 1024*1024);
        }
        for(i=0;i<1023;i++){
            free(ptr[i]);
        }
        getchar();
        return 0;
    }`

I found it does not return memory to OS. I have about 5G free memory before running it. And found I can only run 4 instances, when trying the fifth, another instance will be killed  automatically．
Why this happend? And how should I avoid such trap in real project?

Thanks!

**Comment by pangqingyuan1991** [comment]
`int main(int argc, char *argv[])
    {
        void *ptr[1024];
        int i;
        for(i=0;i<1024;i++){
            ptr[i] = malloc(1024*1024);
            memset(ptr[i], 0 , 1024*1024);
        }
        for(i=0;i<1023;i++){
            free(ptr[i]);
        }
        getchar();
        return 0;
    }`

**Comment by interwq** [comment]
jemalloc by default uses time based [decay](http://jemalloc.net/jemalloc.3.html#opt.dirty_decay_ms) to purge unused dirty memory. In our experience it works well in practice, since memory reuse is frequent in real production workload.

You can change the behavior by setting MALLOC_CONF, e.g. "dirty_decay_ms:0" will return freed memory immediately, likely at the cost of more CPU cycles spent on making syscalls and future page faults etc.
