### ISSUE TITLE
the definition of `arena_run_heap_remove_first` and how to trace full runs

### ISSUE THREAD

**Issue by wenqicao** [jemalloc/jemalloc#1264]
can anyone tell me where is the implementation of function `arena_run_heap_insert` and `arena_run_heap_remove_first`. I can only find where they are called, but still can't find where they are defined. 

moreover, is there any mechanism in jemalloc to track allocated runs. For each bin, only nonfull runs can be tracked, once the run is full, it will be removed from the list. Can I track these full runs using some APIs?

BTW: the version of jemalloc I am using is 4.5

**Comment by davidtgoldblatt** [comment]
The `_remove_first` functions are generated by the macro in `ph.h`. In the 4.5 tagged branch, you can look for `ph_gen(arena_run_heap)`.

I don't think there's an API to examine those heaps. The notion of runs was removed in jemalloc 5.0, so I don't think there will ever be something upstream that's easy to backport.

**Comment by wenqicao** [comment]
I just wanna confirm with you if it works in the following way.
I found `ph_gen(static UNUSED, arena_run_heap_, arena_run_heap_t, arena_chunk_map_misc_t,
    ph_link, arena_snad_comp)` in `arena.c`. I guess this `ph_gen` is used for creating a series of functions, which are implemented in `ph.h` `#define ph_gen` part. So, basically, after `ph_gen` call, jemalloc would create `arena_run_heap_new` `arena_run_heap_empty` `arena_run_heap_first` `arena_run_heap_insert` `arena_run_heap_remove_first` and `arena_run_heap_remove`. is this correct? Thanks

**Comment by davidtgoldblatt** [comment]
Right. (Or, a slightly more precisely rather, the preprocessor expands that out into that set of function definitions).

**Comment by wenqicao** [comment]
thanks 👍 
since what I want to do is tracking all full-runs, I am thinking if I can make it by re-using the current `ph` approach that is now used for managing non-full runs. Specifically, I wanna add one more `ph_link` in `arena_chunk_map_misc_s` for linking all full-runs together. I am wondering if adding one more `ph_link` could impact the size of `arena_chunk_map_misc_s`? do I need to check padding? would such modification impact current infrastructure or not? thanks

**Comment by davidtgoldblatt** [comment]
Hmm, I can't speak with confidence on 4.5, but we have recently tried linking together all extents associated with a given arena, and it does result in a modest slowdown (so that we only do it for non-auto arenas). I'm not sure about the size of the metadata struct, but in our current state it does matter quite a bit (being exactly 2 x86 cachelines for an extent_t at dev). However, you might be able to reuse the link used for non-full slab tracking, since no slab needs to be in both heaps at once.

(I assume this is implied from context, but just to be explicit about it, this is *not* something we'd take as a pull request to stable-4; you'd have to maintain it as an out-of-tree patch set).

**Comment by wenqicao** [comment]
awesome! I like the idea of re-using the link used for non-full run tracking. that's true, no run are in both heaps at the same time. thank you! my problem has been solved. please close the issue 👍

**Comment by davidtgoldblatt** [comment]
Good luck!
