### ISSUE TITLE
object count

### ISSUE THREAD

**Issue by sudurais** [jemalloc/jemalloc#1304]
I've been using jemalloc for few years now. Its pretty good. When I wanted to keep track of C++ objects allocated and freed with simple counter (may be atomic in case of multi-thread), I don't see any such implementation or discussion on jemalloc. Wondering, why isn't needed? May be. But, don't we need a simple stats say, class HelloWorld, how many objects alloc/free for HelloWorld type?. 

How do we go about extending jemalloc with such counters?. 

Thanks,
Suresh

**Comment by davidtgoldblatt** [comment]
I think jemalloc is probably the wrong place for this sort of tracking; by the time the request gets to us, it's been stripped of type information by the runtime / language abstractions. We do provide some counts (see the various stats available in the man page), but they're mostly by size.

Probably best would be to add custom operator new overloads for the specific types you're interested in; this would let you hook allocation / deallocation logic for them in a way that adds counters (and handles threading and atomicity however you'd like).

Closing for now, since I don't think there's a ton we can do here.
