### ISSUE TITLE
bad_alloc due to overcommit setup in sysctl

### ISSUE THREAD

**Issue by egaudry** [jemalloc/jemalloc#1324]
Hi,

I'm working on a strange bug that would results in jemalloc throwing a std::bad_alloc - although there is plenty of physical memory and virtual address space available - for a 'simple' newImpl allocation (of a bunch 64-bit integer through a vector resize and/or reserve).

This would happen when vm.overcommit_memory=2 even with a high vm.overcommit_ratio. By using vm.overcommit_memory=1, the bad_alloc is gone and the Committed_AS value is much lower.

Some work was done for handling overcommit, but is there some corner cases that remained identified ? What would be a good approach to better understand this issue ?

This behavior was seen with jemalloc, 4.3.1, 4.5, 5.0.1 and 5.1.0 on different Linux servers (all 64-bit, kernels 2.6, 3.10, 4.4).

Thanks,
Eloi

**Comment by egaudry** [comment]
might be linked to #1256

**Comment by jsteemann** [comment]
I think the issue is due to jemalloc changing a memory mapping's protection flags from `PROT_READ | PROT_EXEC` to `PROT_NONE` when "committing" memory. It seems to only do so when `overcommit_memory` is set to 2, but not for values `0` and `1`. If I understand correctly, the rationale behind this is to keep the memory around for later reuse and do not return it to the OS using `munmap`. However, changing the protection settings of the committed range may cause page splits, and that may lead to an ever-growing amount of memory mappings.

For jemalloc 5.0.1, the following hack seems to fix the growing number of mappings:
```
index fec64dd01d..733652adf3 100644
--- a/3rdParty/jemalloc/v5.0.1/src/pages.c
+++ b/3rdParty/jemalloc/v5.0.1/src/pages.c
@@ -20,7 +20,7 @@ static size_t os_page;
 
 #ifndef _WIN32
 #  define PAGES_PROT_COMMIT (PROT_READ | PROT_WRITE)
-#  define PAGES_PROT_DECOMMIT (PROT_NONE)
+#  define PAGES_PROT_DECOMMIT (PROT_READ | PROT_WRITE)
 static int     mmap_flags;
 #endif
 static bool    os_overcommits;
```
I am not saying this hack is any good or that I would have well tested it. Additionally it will cause security issues, because memory the application has given back are still readable and writeable afterwards. So please don't use it in production.
I am responding here because I am currently trying to understand and fix the exact same problem in an application. Number of memory mappings for the process grows steadily, so any increased value for `vm.max_map_count` will eventually be reached. This only happens with an `overcommit_memory` value of `2`, and this is understandable when looking at jemalloc's source code. The increase happens both with 5.0.1 and 5.1.0.

**Comment by egaudry** [comment]
Hi, thanks for sharing the results of your investigations. I came to the same conclusions regarding the memory mappings (without checking the implementation details, thus I was very much interested by your post).

The fact that max_map_count will still be reached no matter what is an issue that would need to be fixed somehow, especially for very large allocation patterns (I guess).

I think that Jason implemented those lines in https://github.com/jemalloc/jemalloc/commit/c2f970c32b527660a33fa513a76d913c812dcf7c, it is said to be an answer to https://github.com/jemalloc/jemalloc/issues/193

**Comment by jsteemann** [comment]
@egaudry : yes, it seems to originate from these commits and issues.
I will now open a new issue in this repository to state the problem. I think having applications/users rely on drastically increasing `vm.max_map_count` is not a good option, especially as it will only help for a certain time. Applications may still hit the configured max_map_count threshold, regardless how high it is set.
Let's see if this behavior can be changed somehow, preferably by some option. Or if there is some workaround that does not require adjusting the system settings. I'll leave all this for the experts :smile:

**Comment by egaudry** [comment]
closing in favor of #1328 offering a much better view of the current issue
