### ISSUE TITLE
Does jemalloc suffer from priority inversion?

### ISSUE THREAD

**Issue by wijnandvelzel** [jemalloc/jemalloc#1330]
Hi,
Does jemalloc suffer from priority inversion?

**Background info**
We are currently using tcmalloc in our software. 
We use a lot of threads in our application that need to react within milliseconds (order of 5 ms). Data needs to be ready for communication over a synchronous link. Besides the important threads we have threads with lower priority for logging, further processing etc.. 
In order to not suffer from priority inversion, we slightly tweaked the software to use priority inheritance. Without these changes we saw that occasionally we have a big delay in the latency of out high priority threads.

A drawback we have is that we do not have insight into the memory use of our application over time as  tcmalloc does not release memory back to the OS.
This is the main reason we want to use jemalloc instead. Another one is the profiling of memory and analysis with jeprof.

**Comment by interwq** [comment]
jemalloc is not totally designed for hard real-time computation, however we do care about tail latency in practice.

In terms of priority inversion, we do have spin based locks (also use pthread mutex) so that always count.

To improve tail latency, there are a few things that usually help:
1) enable background thread (see details https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md). This shifts potentially blocking syscalls to bg threads.
2) controlled thread-to-arena binding -- e.g. you can manually create different set of arenas for your high / low pri threads, to make sure low pri threads never cause contention; or even create 1 arena per high pri thread.
3) as you mentioned, returning memory back to OS can be expensive. You can tune the decay time to balance memory purging and cost.
Details in https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md

**Comment by interwq** [comment]
Feel free to reopen if more questions.
