### ISSUE TITLE
Experiment with per CPU arenas.

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#14]
Experiment with using just one arena per CPU, and using sched_getcpu(3) or equivalent as a heuristic when choosing an arena for allocation that cannot be satisfied by the thread-specific cache.  The known challenges include:
- sched_getcpu(3) is Linux-specific.  FreeBSD probably has the necessary infrastructure to implement an equivalent feature, but it does not currently exist.
- Because this strategy for arena selection cannot be implemented on all platforms, the existing arena selection strategy will have to remain as an option.
- If an application runs fewer threads than there are CPUs, a per CPU arena is a waste.  It may be important to transition from one arena selection strategy to another as the number of threads increases.

**Comment by thestinger** [comment]
The best approach that I've come up with is the following:

* 1 arena per core, rather than 4 arenas per core
* assign the initial threads via round-robin, until each arena is used
* when there are no unused arenas, switch to sched_getcpu()
* store the thread ID of the last thread to allocate in the arena

The algorithm for picking an arena for allocating:

```
if thread.last_arena.last_allocator == thread.id && trylock() != fail
    pass
else:
    pick_arena_with_sched_getcpu()
    lock()
set_last_allocator()
```

This results in significantly better load balancing than jemalloc has at the moment while using 1/4 as many arenas. The dynamic load balancing works extremely well because a new "owning" thread for the arena will kick out any stragglers not yet assigned to the correct arena for their core.

(I also mentioned this at http://www.canonware.com/pipermail/jemalloc-discuss/2015-February/001014.html)

**Comment by thestinger** [comment]
The usage of `trylock()` is probably unnecessary with the addition of the `last_allocator` heuristic. It could just do the following to avoid a pointless `sched_getcpu` call due to threads holding the arena lock to free memory:

```
if thread.arena.last_allocator != thread.id:
    thread.arena = pick_arena_with_sched_getcpu()
    lock()
    thread.arena.last_allocator = thread.id
else:
    lock()
```

The `last_allocator` handling would just use `memory_order_relaxed` atomics in C11.

**Comment by poige** [comment]
The CIF allocator mentioned in  "Cache Index-Aware Memory Allocation", by Afek, Dice, and Morrison (ISSM 2011) „… can be configured to use the CPUID or RDTSCP instructions to select a heap. …”, so, possibly the same approach is also suitable for the matter in question. According to Wiki:
„…
Unlike most other CPUID leaves, leaf Bh will return different values in EDX depending on which logical processor the CPUID instruction runs; the value returned in EDX is actually the x2APIC id of the logical processor. The x2APIC id space is not continuously mapped to logical processors however; there can be gaps in the mapping, meaning that some intermediate x2APIC ids don't necessarily correspond to any logical processor. Additional information for mapping the x2APIC ids to cores is provided in the other registers. Although the leaf Bh has sub-leaves (selected by ECX as described further below), the value returned in EDX is only affected by the core on which the instruction is running but not by the subleaf.
…”

**Comment by interwq** [comment]
We added ```opt.percpu_arena``` on the dev branch, and will ship it in 5.0 release. After some production testing, we observed that the feature results in slow down in some cases with the current implementation. We will make it disabled by default (#848) for now, and investigate further separately in #713.
