### ISSUE TITLE
Add "conf_print:<bool>" option

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#1492]
It seems like a nontrivial fraction of questions we receive are "I'm tweaking malloc_conf settings, but it seems like something is making them not take effect; how can I check?". The easiest way is to set `stats_print:true`, but lots of people have binaries that never exit, or that are crashing.

Another thing we could do is add an option to print the configuration as soon as we've parsed it, at program startup. This would be a quick and easy way to check without requiring re-building.

**Comment by jasone** [comment]
Another trick is to specify a known-bogus configuration string to make sure a warning is printed, e.g. `MALLOC_CONF=no_such_opt:XXX ...`.  In fact, such warning messages commonly come up in a less desirable context when testing a custom build on FreeBSD, because e.g. heap profiling isn't built in to libc.

**Comment by interwq** [comment]
Done by Yinan in #1498.
