### ISSUE TITLE
leak_check profiling much more expensive between jemalloc-3.6.0 and jemalloc >= 4.2.1

### ISSUE THREAD

**Issue by pavlarez** [jemalloc/jemalloc#1530]
I recently upgraded to jemalloc 4.2.1. I have also tested this with 4.5.0 and 5.1.0 and seen similar difficulties with all of them.

In 3.6.0, turning on profiling with parameters MALLOC_CONF="prof_leak:true,lg_prof_sample:0,prof_final:true" causes a very small increase in memory use, about 5%

In 4.2.1, the same code now sees a 2500% increase in memory use.

Is this expected? Have some default parameters changed so that I need to set them to avoid this huge increase in memory?

Thanks

Pablo Alvarez

**Comment by davidtgoldblatt** [comment]
Setting lg_prof_sample to 0 means "sample every allocation and record a stack trace"; is that intentional? I would expect a large memory regression in that case. A more typical value for that might be in the 18-22 range.

I'm not sure why you don't see that regression on 3.6; perhaps the handling of the 0 case has been changed since then.

**Comment by jasone** [comment]
We changed the memory layout for sampling between 3.x and 4.x.  In 3.x, if sampling was enabled at a high enough frequency, all small allocations had a associated sampling metadata pointers.  In 4.x, only large allocations have such metadata, and sampled small allocations are actually promoted to slabs (i.e. 4KiB per sampled allocation).  The memory overhead for high sampling rates is very high after the 3.x series, but in practice high sampling rates were only useful for precise leak count reporting, and that use case is better served by e.g. Valgrind.

**Comment by pavlarez** [comment]
Thanks, that's very helpful. I was sampling at max rate because this was a
unit test. I will take a look at more reasonable production-like use cases
and see what I get.

What was the reason for the change, by the way?

**Comment by interwq** [comment]
re: the reason behind changing the metadata for sampled allocation -- I believe it's mainly because that very high sample rate is not expected in production environment, and like Jason mentioned when really needed it's better served by other facilities. In the meantime, trying to support / optimize for high sample rates adds a bunch of implementation overhead; by assuming that sample allocations to be uncommon, it allows us to simplify the profiling logic (e.g. simply bump the small sampled to slabs).
