### ISSUE TITLE
When will the next jemalloc version be released ?

### ISSUE THREAD

**Issue by ldcsaa** [jemalloc/jemalloc#1793]
Please tell ...

**Comment by thefallentree** [comment]
bump!

**Comment by todd-richmond** [comment]
Any progress on this since release > 2 years ago? It is impossible for the general world to know when the repo is safe to pull from so we are all stuck on 5.3.0
A 6 month release cycle would be great if possible

**Comment by interwq** [comment]
No new release is planned in the near future. There are quite some development ongoing (e.g. around huge pages), but these may take a while to finish and fine tune. If you'd like to try the most recent versions, https://github.com/jemalloc/jemalloc/issues/2060 contains pointers to the production-tested commits.

Note that the release frequency is lower since 5.0, mainly as a result of the improved CI coverage. This was called out in the 5.0 release note:
https://github.com/jemalloc/jemalloc/releases/tag/5.0.0

**Comment by todd-richmond** [comment]
it would be a great help to make those actual releases since having to know a magic issue link is completely hidden. If it is being used in deployment, that is pretty much the definition of a "release".
I maintain 250 open source component builds and only Jemalloc, RapidJSON and 2 obscure repos require pulling random commit revs from github. All the rest have at least yearly releases if still in active development
Please at a minimum put a link to #2060 in the top level Readme - thx

**Comment by interwq** [comment]
@todd-richmond unless you care about the most cutting edge updates and run your software at a very large scale (where every % matters), you shouldn't try the commits in #2060. 5.3.0 is still recommended for general purpose usage. jemalloc is a very low level component and we don't expect the release to be as  frequent comparing to other projects . If there are any notable bugs we will do bugfix releases.

**Comment by todd-richmond** [comment]
we have a very malloc intensive application running on about 50000 vms and hardware nodes (multi-threaded perl and c++ as well as mariadb). We found jemalloc to eliminate multi-threaded bloat caused by glibc malloc and have better perf. We also tried mimalloc and tcmalloc based on tests around the 5.3 timeframe and jemalloc won out, but both are also under active development and it is time to evaluate again
mimalloc uses tags instead of official, full releases which also works well
