### ISSUE TITLE
Question: Is it possible to force jemalloc to use hugepages

### ISSUE THREAD

**Issue by kreuzerkrieg** [jemalloc/jemalloc#1935]
I mean 1GiB pages, looks like `jemalloc` can use transparent huge pages out of the box. However I didnt find any evidence it can use 1GiB huge pages. In case it is not supported, is there a way just to feed the starting pointer and give it available memory size which I obtain from `mmap`?

**Comment by interwq** [comment]
For 1G pages, we don't have anything built in directly. You can achieve the goal with adding a manual arena with customized [extent hooks](http://jemalloc.net/jemalloc.3.html#arena.i.extent_hooks), so that it asks new mappings from the reserved regions instead of `mmap`; for example [HHVM does this](https://github.com/facebook/hhvm/blob/master/hphp/util/extent-hooks.cpp#L101). Note that you may want to carefully manage the arena as fragmentation is often a concern with 1G pages.

Closing but feel free to ask.

**Comment by kreuzerkrieg** [comment]
Finally got to the code. Not exactly what I want, extent hooks intended for single arena management (correct me if I'm wrong) behavior override. I'm looking for something more global, like I'll do the `mmap` allocating all available memory, like 120GiB out of 128 on the machine, provide `jemalloc` with start address and the region length, now go and manage it from above region as `jemalloc` always does and dont try to allocate any additional memory.

**Comment by HappyRustacean** [comment]
@kreuzerkrieg  For this use case, do you currently have a solution?

**Comment by kreuzerkrieg** [comment]
> @kreuzerkrieg For this use case, do you currently have a solution?

nope
