### ISSUE TITLE
Allocate from a big continuous chunk of memory that has a few small holes

### ISSUE THREAD

**Issue by tamirzb** [jemalloc/jemalloc#2052]
Hello,

I have what is essentially one big `mmap`, and I would like to create a custom jemalloc arena that allocates memory from that `mmap`. The catch is that some pages in that `mmap` are already used, which basically create a few holes in the `mmap` of size of  a page where I can't allocate memory from. Is there a way to still allocate from the rest of the pages in the `mmap`?

I looked into the API and the custom extent hooks but I didn't find a way to do it. The best thing I could think of is to set `arena.<i>.retain_grow_limit` to the size of a page, but apart from that probably being really bad for performance, it also doesn't completely work for me. On the arena creation it seems to immediately ask for an extent of 2 MiB and fail if it doesn't get it. While there's a good chance my `mmap` will start with 2 MiB of free space, I can't guarantee that.

Is what I'm asking for possible with jemalloc in any way?

**Comment by everschen** [comment]
I have looked into this several days back, for my understanding is by default retain is enabled, then system will allocate 2M/4M extent memory each time if the request size is small than 2M/4M, later any small memory request will be allocated from that extent until the extent memory is used up, then it will come to the next extent memory.
so I am not sure for your situation, do you mean first several pages was used, then come to the request for 2M? if this is the case, then the 2M request will be allocated in another new extent I believe, any concern for this case? or do you mean the later request will always be 2M?

**Comment by tamirzb** [comment]
I'm not sure I managed to explain myself correctly. I'll give a situation as an example.

Let's say I have many many chunks in memory which I would like to give as extents. These chunks vary in size, but they are all smaller than 2M. When I try to create an arena, it asks for a continuous memory of 2M, which I don't have. Is there any way to still do what I'm asking?

**Comment by everschen** [comment]
If you take a look at the latest dev code, the chunk concept has been totally removed, replaced with extent, the extent could be slab or not (other data). the default 2M retain case is not slab here.

if one block was used  (as a slab) from the extent, then the extent will be split into two or three part, the slab and other remain part. this is like the concept of run before.

so for your situation, if there's many chunks (extents), I believe it should be the extent which part of space was free back to jemalloc, as you know if there's free space left could be used in the extent, jemalloc will not request new extent, even more, it will make sure always use the lowest virtual memory address. However for no continuous memory of 2M, it depend on the merge policy, if it can't be meet finally, then it will request from the system.

David @davidtgoldblatt , correct me if my understanding is wrong.

**Comment by interwq** [comment]
I think @tamirzb was asking about the custom extent hooks, not the `chunk` in the previous (before 5.0) jemalloc design.

If I understand correctly, then `retain_grow_limit` is probably the best bet. The current retain design is to avoid creating too many separate mappings (in other words, to avoid holes in VAS for kernel, since there's a limit on # of `mmap`ed regions), as well as giving jemalloc flexibility on virtual address space management (e.g. to ensure first-fit policy, we disallow merging across different `mmap` regions). So very low retain_grow_limit will have bad impact on performance. Will setting it to 0.5 or 1M work for your use case?

If you observe higher sized alloc happening at the beginning of the program, that should be part of the initialization, e.g. allocating the internal radix tree nodes.

The other direction, is to disable retain (e.g. with `MALLOC_CONF=retain:false`). However that comes at other costs, and we do plan to make `retain` the global default across all platforms.

In the long term, I think this is another limitation of the current extent_hook API. We have a number of ideas listed in #1009. Please feel free to add comments there as well. In the next major release (6.0) we'll likely rework the hooks, e.g. to allow the alloc_hook returning sizes in between [minimal_size_to_fulfill_current_request, ideal_size_to_grow_retain]. However it will take some time to happen.

**Comment by interwq** [comment]
Closing but feel free to ask.
