### ISSUE TITLE
Question for low number of arenas

### ISSUE THREAD

**Issue by mrdotmoon** [jemalloc/jemalloc#2056]
I have 8 threads to load data into memory from remote cloud blobs, and they allocate long live small objects. It looks like this malloc pattern causes a lot of fragment as the metadata is increasing dramatically after few days. After using an explicit arenas, it do improves a lot the fragment.
My question is, since all those memory are allocated in a single arena and thread, for other threads which access those memory, will it cause a lot of lock contention?

**Comment by interwq** [comment]
The lock contention happens when you have multiple threads reaching the arena level at the same time. In your case with the explicit arena, if multiple threads trying to allocate together, they may contend on the bin lock (if allocating the same size) and / or the page cache lock. Or even if you only have one thread allocating, other thread may deallocate which returns memory to the original arena. So the deallocation may cause contention as well.

To better understand the impact from locking, you can try 1) malloc stats, which has [mutex counters](http://jemalloc.net/jemalloc.3.html#mutex_counters), and 2) `perf record` which can tell you how much CPU the locking takes.

Closing but feel free to ask anything.
