### ISSUE TITLE
microbench should use clock_gettime instead of gettimeofday

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#208]
Note that neither clock_gettime nor gettimeofday are available on Windows, but at least clock_gettime is saner for benchmarks. There's an example clock_gettime implementation for Windows on http://stackoverflow.com/questions/5404277/porting-clock-gettime-to-windows and that being stackoverflow, the user contribution is cc-by-sa 3.0 with attribution. No idea how compatible that is with 2-clause BSD.

**Comment by thestinger** [comment]
I made this as an attempt to fix a bias issue but didn't submit it because it didn't make a difference:

https://github.com/thestinger/jemalloc/commit/c1ffec2998a657d73c9bd1f4b2bf6d9f4412eade

It's technically more suitable than `gettimeofday` since it won't get screwed up by a time shift and has nanosecond precision, but in this case it doesn't matter much.

It can be applied if it's viewed as useful.

**Comment by jasone** [comment]
```clock_gettime()``` is now used when available: d6384b09e137874d7cdf527e5bb50abba0ae5f95
