### ISSUE TITLE
Where is the guide for iOS??

### ISSUE THREAD

**Issue by gaxlin** [jemalloc/jemalloc#2086]
I can not see how to compile jemalloc for iOS targets from the install document.

**Comment by davidtgoldblatt** [comment]
Unfortunately, compiling on iOS is fairly difficult because of the execution environment restrictions[1]. I wouldn't recommend it for general purposes right now.

You can see some of the hacks you have to go through in https://github.com/jemalloc/jemalloc/pull/2000 and https://github.com/jemalloc/jemalloc/pull/2001 .

Closing since I think we realistically don't have the engineering hours to make this easy in the near future, but happen to be around to bounce ideas off of if you're interested in pursuing it.

[1] Well, *compiling* is easy; *running* is hard.
