### ISSUE TITLE
Aerospike for Major Users page

### ISSUE THREAD

**Issue by PeterCorless** [jemalloc/jemalloc#212]
For this page:

• https://github.com/jemalloc/jemalloc/wiki/Adoption

Can you also add Aerospike? q.v.:

• http://highscalability.com/blog/2015/3/17/in-memory-computing-at-aerospike-scale-when-to-choose-and-ho.html

Thanks! -Pete Corless.

**Comment by thestinger** [comment]
Android is using it as the default in their C standard library since 5.0, FWIW:

https://github.com/android/platform_bionic/commit/8e32b7b3543eadbb58a92443fb57d60aac92ef88

They cap the number of arenas at 2 and make the thread caches smaller:

https://android.googlesource.com/platform/external/jemalloc/+/d481006e6fe6ba1316f72d71f51580507d44ef4f%5E%21/#F3

There's also a `mallinfo` implementation:

https://android.googlesource.com/platform/external/jemalloc/+/e5d3dcfe0dbd2515afaa88f1b77c1eb0b88a40c0/android/src/je_mallinfo.c

**Comment by jasone** [comment]
Aerospike and Android are now listed.  Thanks!

**Comment by PeterCorless** [comment]
Awesome! Thanks!
