### ISSUE TITLE
Tuning question: How to adjust region number of per slab size class?

### ISSUE THREAD

**Issue by AndroidInternal** [jemalloc/jemalloc#2131]
Hi, all.

Thanks for the excellent allocator and detailed document, but I still have a question when tuning my Android Application.

I find a truth that each size class slab has a fixed region number and sum of these regions are 4k pgae size alignment , for example :

![image](https://user-images.githubusercontent.com/3592681/134641301-fec7a887-e89c-4746-b8a7-90a4cf2c4a9b.png)

The regions number of per slab size class seems to be no other regular pattern except for per size class slab size must be alignment with page size.

And what's more, each bin has a ncached_max upper limit by twice of regs:

![image](https://user-images.githubusercontent.com/3592681/134641879-d9e49862-5922-43ad-8c53-3d2cb5d4d7eb.png)

So I'm wondering whether it is allowed to adjust region number size bigger to reduce tcache fill times, and then it is supposed to have some performance improvements other than I have some misconception on jemalloc. 

For example, size class 64 byte has a region number of only 64 and ncached_max has an upper limit of 128.

Thanks.

**Comment by Lapenkov** [comment]
Hi, thank you for your question.

Region number per size class is a fixed value - it's equal to `(slab size) / (region size)`. Slab size and region size depend on size classes, which are hardcoded. You can't modify this ratio.

Since 5.2.1, this policy of `ncached_max = nregs * 2` has become (unofficially yet) modifiable. You can set `lg_tcache_nslots_mul`, `tcache_nslots_small_min` and `tcache_nslots_small_max` via malloc conf. So if you build from upstream, you will be able to use these configuration settings. But these are not documented yet, so they are **subject to change**. _**Do not rely**_ on these staying unmodified and being released in the next release.
