### ISSUE TITLE
Question: Memory leak detection

### ISSUE THREAD

**Issue by vpshastry** [jemalloc/jemalloc#2162]
One of our services is leaking / exhausting memory and OOM killed. The service uses jemalloc which is quite handy in detecting such issues.

I read both https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling and https://github.com/jemalloc/jemalloc/wiki/Use-Case:-Leak-Checking. 

After reading I had few questions below.

1. https://github.com/jemalloc/jemalloc/wiki/Use-Case:-Leak-Checking asks to enable prof_leak and prof_final. Apart from the problem described with atexit <-> memory allocation deadlock with prof_final, is there anyway I can on-demand dump the information that prof_final automatically does at exit?

2. From your response (http://jemalloc.net/mailman/jemalloc-discuss/2015-February/001027.html) I kinda got the idea that opt.prof and opt.prof_leak both refer to heap profiling. Is it true? Is the information dump done by prof_final and prof_leak same as analyzing the opt.prof heap dump? (This also answers one of the question asked by http://jemalloc.net/mailman/jemalloc-discuss/2015-November/001204.html)

Thanks in advance

**Comment by Lapenkov** [comment]
Hello, thank you for the questions.
1. You absolutely can do that. To perform a memory dump at an arbitrary moment, you can call `mallctl("prof.dump"...)` in your application.
2. Yes, these both options refer to heap profiling.`prof_leak` simply reports if the final dump is non-empty, i.e. not all objects have been free'd by the time your application gracefully exits.

But aside from your direct questions, I want to ask you to reconsider the approach. You can't rely on `atexit` if your application is killed by the OOM killer, because `atexit` is not called in this case. Better to just analyze interval-based dumps (see `opt.lg_prof_sample` and `opt.lg_prof_interval`). You can take two such dumps and see their diff, in that diff you'll see which objects remained on heap between two points in time. That could expose memory leaks.

**Comment by vpshastry** [comment]
Thanks @Lapenkov . Yeah after reading more, I'm taking that approach. Thanks for the suggestion.

**Comment by interwq** [comment]
Closing but feel free to ask if anything.
