### ISSUE TITLE
How about reserve all memories we need for less performance impacts when THP enabled?

### ISSUE THREAD

**Issue by hustbeef** [jemalloc/jemalloc#2172]
Jemalloc tries to use transparent hugepages when options thp or metaspace_thp is enabled. However, I've seen several cases that encounter performance performance when using THP. I'm trying to eliminate such impacts by reserving all memories jemalloc needs once it initialized.
As far as I know, THP impacts performance in four ways:
1. In the PAGE_FAULT where allocating high order pages,  direct reclaim/compaction tooks too much time. 
2. Transparent Hugepage allocations wake up the kcompactd thread more frequently. This increases the sysload.
3. Compaction will isolate movable pages and then migrate them. Meanwhile, every load/store request will be stalled until compaction finished.
4. Khugepaged will try to compact more huge pages. It may cause the same problem as the third concern.

I think all concerns I mentioned can be avoid by reserving memories at initializition.  Arenas allocate extents from the reserved memories. Physical memories are reserved so that no more PageFaults are needed.

Am I doing the rignt thing? It seems like a simple way to reserve memories. It's also helpful for sharing memories between arenas. So I'm not sure if it is a great design.

Discussions are welcome.

**Comment by interwq** [comment]
Reserving memory would imply taking up resources we don't know if / when will get used. Although it reduces impact potentially on the CPU side, the memory cost will be high from the reservation, especially when there are multiple applications co-located on the same host. 

You can try this MALLOC_CONF setting to achieve a similar behavior: `metadata_thp:always,dirty_decay_ms:-1,muzzy_decay_ms:-1`. This disables dirty page purging, i.e. page cache will stay around forever. Also will try to use huge pages for metadata eagerly, but won't over-reserve since we don't know how much will be needed.

**Comment by hustbeef** [comment]
In dev branch, I've seen this comment in src/hpa.c:
    * I think the ideal setting is THP always enabled, and defrag set to
    * deferred; in that case we don't need any explicit calls on the
    * allocator's end at all; we just try to pack allocations in a
    * hugepage-friendly manner and let the OS hugify in the background.

I stiil think pretouching is a considerable solution for such concern. Maybe pretouch memories once hpa_central_t tries to mmap it's eden area. Also use background threads to do it to avoid long allocation latency.

Looking forward to your comments. Thanks.

@interwq @davidtgoldblatt
