### ISSUE TITLE
Ability to tune oversize decay

### ISSUE THREAD

**Issue by awused** [jemalloc/jemalloc#2208]
I ran into some significant performance regressions switching to jemalloc 5.2.1 from 5.1 when oversize_threshold was added since those pages are purged immediately. My application happens to have a decent number of relatively large allocations, and allocating/freeing them can be in the critical path. Some of them aren't directly under my control and aren't easily converted to using a manually specified arena (#1979 wouldn't resolve my problem, not easily).

If I were able to set non-zero decay thresholds for oversize allocations that would avoid my problem and put me in a better place than 5.1, with the large allocations in a single arena but reusable.

**Comment by Lapenkov** [comment]
Hello. Thanks for the question.

There's no decay for oversized allocations, currently it's implemented in such a way that if an allocation is categorized as `oversized`, it's instantly purged. I think the only way for you to avoid the regression is to disable oversize threshold.

If you really want to have a separate arena and decay, you can try patching your jemalloc by removing this `if`:
https://github.com/jemalloc/jemalloc/blob/dev/src/extent.c#L926
I haven't tried it though and wouldn't recommend unless you want to risk the stability and compatibility with further upstream updates.

**Comment by awused** [comment]
I'm aware that there isn't currently a way to configure it, but it seems like it could be useful not just for my own application but for others. If it's just a matter of taking an if branch or not, then even a very simple boolean toggle to use instant decay or the other configured global decay settings seems reasonable since it's a performance trap even if the default behaviour is fine for most applications. I'm currently setting `oversize_threshold` to 0 to maintain 5.1 behaviour.

Right now the documentation mentions `Note that when the oversize_threshold feature is enabled, the arenas reserved for oversize requests may have its own default decay settings.` which is technically true, but right now they don't just have a default value, they have a hard-coded non-override-able logical value of 0.

**Comment by interwq** [comment]
I'm a bit hesitant to add a decay setting specifically for the oversized arena, since it limits our future design choices, and the wording in the manual is there exactly to say that it may change internally (e.g. may not be a time based decay, but rather a size based limit).

However, right now you can change the decay time, not through runtime options but through `mallctl`s on the fly:
1) read the `oversize_threshold` setting through `mallctl("opt.oversize_threshold", ...`
2) allocate a buffer using the size returned above
3) make another mallctl to look up the arena id of the allocated buffer: http://jemalloc.net/jemalloc.3.html#arenas.lookup
4) the returned arena index is the dedicated arena to serve oversized allocations, and can be tuned like regular arenas, including the `arena.<i>.dirty_decay_ms` http://jemalloc.net/jemalloc.3.html#arena.i.dirty_decay_ms

The other option could be to increase the oversize_threshold, instead of disabling it completely. Or like Alex suggested, tweak and build a custom jemalloc with the settings you want: https://github.com/jemalloc/jemalloc/blob/dev/src/arena.c#L1731-L1738

**Comment by awused** [comment]
Neither of those seem like great options. Given the wide array of tunables jemalloc exposes this seems like an odd blind spot that can cost significant performance for users on the default configuration. I'd not done any jemalloc tweaking besides switching from 5.1 to 5.2.1.

As a direct consequence of disabling `override_threshold` I was seeing 15-30ms improvements in user-visible latency depending on the size of the images I was wrangling. This is a desktop application, so it directly translates to 2-8 frames of delay depending on the user's refresh rate. That's only from the cost of freeing pages that is delayed: if I get lucky and happen to reuse an earlier allocation from the start I can see well over 100ms in latency improvements, though I don't set `narenas:1` to force this so I usually do not see such huge improvements.

**Comment by awused** [comment]
I was actually wrong, because I am using a single thread for making and freeing many of the largest allocations per operation I actually more commonly see the greater savings in practice and luck isn't as large a factor. I tried to avoid overstating the performance differences.

And to elaborate on why these aren't good options:

* Raising oversize_threshold compared to disabling it
  * This completely fails to solve the performance problem. Pages for large allocations can't be reused since they're freed immediately.
  * I'll either increase it so much it's effectively disabled, offering no benefit, or I'll not increase enough in which case I still have poor performance on the largest allocations, where the performance penalty is the largest.
* Looking up the arena and changing its settings.
  * Now I need to spent most of a hundred milliseconds on application startup just to make sure I'm not wasting time later.
  * You've said yourself that the oversize arena is handled specially and could change in the future.
  * It doesn't sound trustworthy and this sounds like a recipe for memory corruption later on.
* Forking jemalloc myself
  * I'd rather not commit to maintaining a fork since, as you've said, I'll risk compatibility and stability.
  * I only updated from jemalloc 5.1 to 5.2 (using the Rust crates) because I observed, and can reproduce, memory corruption in my applications with the max_background_threads option on 5.1, so I'm just not willing to trust a non-standard jemalloc config.

**Comment by Lapenkov** [comment]
I don't think we can offer any other options, unfortunately. Sorry that none of that works for you, you're welcome to pick whatever has the least number of the drawbacks you listed above.

**Comment by awused** [comment]
Well, I've already chosen none of them. I've chosen to disable oversize_threshold because it causes regressions that are noticeable to the naked eye (unlike https://github.com/jemalloc/jemalloc/issues/1621#issuecomment-529503537 which was only obvious in benchmarks). You also certainly could offer other options - that's what this feature request was for - you've just chosen not to, but I'll respect that and not push further.

**Comment by davidtgoldblatt** [comment]
To expound a little, I don't think Alex means "we're not gonna work on the general problem" so much as "we don't want to fix that problem in this particular way". The long-term goal is towards more centralization of purging policies, so that this problem can get addressed a little more straightforwardly, especially for larger sizes; `oversize_threshold` is a little bit of a hack on its own. Piling hacks on top of it adds extra work (both for us and for people who've adjusted the setting) when we try to start unwinding some of this.
