### ISSUE TITLE
zero_realloc option naming

### ISSUE THREAD

**Issue by davidtgoldblatt** [jemalloc/jemalloc#2223]
Now that `realloc(ptr, 0)` is UB per C23, calling the mode that acts like malloc(0) "strict" (originally meant in the vein of "strictly conforming to the standard semantics") is sort of weird. I think 5.3 will be the first release with this option; maybe we can sneak in a better name under the wire.

Maybe "malloc", so that the options are `zero_realloc:malloc|free|abort`. That has kind of a nice symmetry; in the first case, realloc(ptr, 0) is sort of like a malloc; in the second, realloc(ptr, 0) is like a free, and in the last, realloc(ptr, 0) is an abort.

I dunno, maybe that's overly cute.

**Comment by interwq** [comment]
I like the `malloc|free|abort` naming, quite straightforward. It's true that 5.3 will be the first version to include it.

We have the option documented in the manual, as expected. https://github.com/jemalloc/jemalloc/blob/dev/doc/jemalloc.xml.in#L1575
But given that it's UB in C23, do you think we should make it experimental or so, maybe even undocument it @davidtgoldblatt?

**Comment by davidtgoldblatt** [comment]
I think we should keep documenting it; basically every platform has *some* guarantee that they document. It's only UB because different platforms chose *different* behaviors, so that portable code can't assume anything; we should probably do the same (and just let users tell us what they expect).

It's probably also worth picking the default to try and match the platform (e.g. zero_realloc:free by default on Linux, zero_realloc:strict/malloc on BSDs, etc.)

**Comment by interwq** [comment]
After the most recent discussion, possible names for the first option: `malloc`, `alloc`, `realloc_1`.

**Comment by Lapenkov** [comment]
Thinking about it retrospectively, I'd say I like `realloc_1` the most, because that is literally what it does.

**Comment by Lapenkov** [comment]
@interwq @davidtgoldblatt if you both like `realloc_1` and don't deem it unacceptably weird (`realloc_zero:realloc_1` indeed sounds quite weird if you don't know the context), I can change it.

**Comment by davidtgoldblatt** [comment]
Honestly every time I see this I come to a different conclusion. realloc_1 is semantically different from realloc(ptr, 1), because in the former you're not allowed to use the pointer (even if it's non-null, you're not allowed to dereference it).

My final naming suggestions: `realloc_zero:allocates|deallocates|aborts`? (Or maybe "frees" instead of "deallocates"?) Describes the behavior rather than trying to summarize it in terms of a different function?

Really though I don't have any strong preference, and I'm not sure that any name is actually good.

**Comment by Lapenkov** [comment]
Right, I forgot that there's such difference. Well, in this case, I think your final suggestion is the best.

**Comment by interwq** [comment]
>  Describes the behavior rather than trying to summarize it in terms of a different function

Agreed. Let's abbreviate though; how about `alloc | free | abort`? We have `opt.junk` which takes `alloc | free`.

**Comment by Lapenkov** [comment]
Fine by me, consistency is important

**Comment by interwq** [comment]
Summarizing more offline discussion around the default options:
1) `alloc`: the current default we agreed on. This avoids security vulnerabilities, at the cost of 0 sized realloc will cause leak if the application expects the `free` behavior. In order to limit and quantify the potential damage, `tcache` is bypassed on such allocations, plus adding a new counter `stats.zero_reallocs`.
2) `free`: this is the previous default, and the default behavior on Linux.
3) platform dependent -- setting the default based on the common behavior on that platform. FreeBSD and MacOS already default to `alloc`, while Linux and Windows are on `free`. 

Although the current default is (1) `alloc`, the other two options as default have their merits as well: (2) `free` would mean the default behavior remain unchanged and least surprising when upgrading; (3) would match the behavior as the system allocator.
