### ISSUE TITLE
Using malloc_stats_print to get per-arena stats for all arenas

### ISSUE THREAD

**Issue by mdcallag** [jemalloc/jemalloc#2329]
The version of jemalloc that I use has 4 arenas per CPU by default which means there are tens to hundreds of arenas on a many-core server. I see [in source](https://github.com/jemalloc/jemalloc/blob/36366f3c4c741723369853c923e56999716398fc/src/jemalloc.c#L4105) that STATS_PRINT_BUF is 64kb so I wonder how I can get results for all arenas with such a small buffer.

My current workaround is to write code using mallctl to get the per-arena counters that I care about. Is there a better way? 

If not, can malloc_stats_print be enhanced to let a caller select results only for one arena via flags in the opts parameter?

**Comment by davidtgoldblatt** [comment]
That buffer is just for *internal* buffering (i.e. so that we don't do a whole bunch of very small calls to the user-supplied print function; this can be helpful for users who are doing a simple uncached passthrough to file APIs or whatever). We'll reuse that buffer many times in invocations to the user write callback; total output isn't limited to 64k (and indeed -- in many use cases with lots of arenas we'll generate lots of stats output; we've seen multiple megabytes worth). Maybe you're assuming one-off semantics in your `write_cb` callback?

My inclination is to try pretty hard to avoid adding anything requiring nontrivial parsing and filtering to malloc stats printing (one of its benefits is that it's easy for *us*). I sort of think that at the point where users are slicing and dicing the data themselves it's OK to ask them to do a little bit of the formatting work, too.

**Comment by mdcallag** [comment]
I was assuming one-off semantics in my mental model of the behavior. But in practice, while I have yet to find the source of the jemalloc that I use, I get ~130kb of results for an implementation that allows for the callback to be invoked multiple times.

From upstream I see that [stats_arena_print](https://github.com/jemalloc/jemalloc/blob/a0734fd6ee326cd2059edbe4bca7092988a63684/src/stats.c#L1845) does what I want it to do.

But in practice I see the callback stop in the middle of printing an arena based on tracing I added to my callback. Perhaps I am using a modified version of upstream.

So I will close this because upstream looks fine. Thanks for the reply.
