### ISSUE TITLE
Deadlock on fork processes inside jmalloc

### ISSUE THREAD

**Issue by MeirShpilraien** [jemalloc/jemalloc#2402]
Hi

We encounter a strange issue on [RediSearch](https://github.com/RediSearch/RediSearch) where our fork processes got hang trying to acquire some lock inside jmalloc. Here are the trace where the fork got hang:
```
0x560ed is in je_malloc_mutex_lock_slow (include/jemalloc/internal/atomic.h:69).
0x4aca0 is in extent_split_impl (include/jemalloc/internal/mutex.h:205).
0x4af8f is in extent_split_interior (src/extent.c:972).
0x4d853 is in extent_recycle (src/extent.c:1026).
0x4f0e8 is in je_extents_alloc (src/extent.c:514).
0x1526d is in je_arena_tcache_fill_small (src/arena.c:1127).
0x75ca4 is in je_tcache_alloc_small_hard (include/jemalloc/internal/cache_bin.h:91).
0xcc77 is in calloc (include/jemalloc/internal/tcache_inlines.h:62).
```

We are running with jmalloc-5.1.0. We though it might be related to this issue which was fixed on 5.3, but we are not sure and would like your advice.

> Fix the locking on the arena destroy mallctl, which could cause concurrent
arena creations to fail. This functionality was first introduced in 5.0.0.
(@interwq)

In our case we have multiple threads on the main processes that might allocated memory. We create a single threaded fork and the fork never creates more threads. This is issue very rare, we saw it on a very limited cases and only recently were able to get a trace.

We would like to understand whether you believe this issue was solved on 5.3 or not. Also, if we think it was not solve, what other information we can extract for the next time it will happened that will help solving it?

Thanks,
Meir.

**Comment by MeirShpilraien** [comment]
This is the issue we found that look similar but we are not sure: https://github.com/jemalloc/jemalloc/issues/2019

**Comment by oranagra** [comment]
@interwq can you please take a look?

**Comment by interwq** [comment]
> This is the issue we found that look similar but we are not sure: #2019

This could be the same issue. That's also the only case I can think of. To make sure, you are seeing child process hanging, right? If so I believe that issue is probably the cause, and 5.3 have it fixed.

**Comment by oranagra** [comment]
Yes it was the child process that hanged.
However the line in the release notes confused me.
I don't think we're using arena destroy mallctl or concurrent arena creations in that flow. But maybe you're referring to something internal, or maybe this is caused by other related bugs solved by that same commit.

**Comment by yangyingchao** [comment]
> 

I'm using jemalloc-5.3, and I recently met a crash too. I think the stack trace in my case look similar to yours, but I'm not sure, because debug symbols are stripped in my case. But I'm sure it differs from #2019, with only 8 stacks from malloc to pthread_lock...

**Comment by interwq** [comment]
@yangyingchao the issue you described sounds like a more common heap corruption to me. The issue in this thread and in #2019 will only occur post fork in the child process, and should result in a deadlock instead of a crash. For your case I suggest trying sanitizers such as ASAN to investigate, or try the jemalloc debug build.

**Comment by interwq** [comment]
> Yes it was the child process that hanged. However the line in the release notes confused me. I don't think we're using arena destroy mallctl or concurrent arena creations in that flow. But maybe you're referring to something internal, or maybe this is caused by other related bugs solved by that same commit.

Oh actually #2019 isn't related to the arena_reset fix in the release notes at all. It was a separate issue and apparently I failed to call it out in the bugfix section of the release notes. #2037 was the PR that fixed it, and somehow I only listed it as  "Optimize the internal locking on extent management." in the release notes.

Sorry about the confusion there.

**Comment by oranagra** [comment]
@interwq thanks! maybe you have an idea what could trigger it in redis? It's very rare and the fix isn't small, so we need to decide when to upgrade.

**Comment by yangyingchao** [comment]
> 

will do. Thanks!

**Comment by interwq** [comment]
> @interwq thanks! maybe you have an idea what could trigger it in redis? It's very rare and the fix isn't small, so we need to decide when to upgrade.

The deadlock would be triggered if at the exact point of fork(), another thread is holding one of the mutexes in the mutex_pool (which is sharded by the vaddr of the allocations). This would result in that specific mutex being in a inconsistent state in the child process (typically in a locked state, but the owner threads is gone after fork). So not quite straightforward to say the exact behavior that triggers that issue.

For the context, in jemalloc's atfork handlers, we take all internal mutexes pre-fork -- this allows malloc / free to continue working after multithreaded fork. However in this case we made a wrong assumption that the mutex_pool locks are always held while holding another state-based mutex (it started that way, but changed later), this was why we believed it was safe to exclude the mutex_pool in the atfork handlers (an attempt to make it less expensive).

For an alternative / temporary workaround w/o upgrading jemalloc, you can try avoiding any malloc / free calls in the child process. Technically they are not allowed since only async signal safe operations should happen in the child, but it's a rather common need and we have always tried to supported the use case.

**Comment by MeirShpilraien** [comment]
Thanks for the help. We upgrade the jmalloc version. Closing the issue.

**Comment by interwq** [comment]
You are welcome!  Feel free to let us know if anything

**Comment by oranagra** [comment]
@interwq do you happen to know which Jemalloc version introduced that deadlock? did it exist in 5.0 too? or even before that?

**Comment by interwq** [comment]
@oranagra It started with 5.0, which needed the mutex pool for vaddr based extent locking. Previous versions didn't have the mutex pool design.
