### ISSUE TITLE
 Unable to Trace Python Function Calls in Jemalloc Heap Profiling

### ISSUE THREAD

**Issue by samannazz** [jemalloc/jemalloc#2450]
I am using jemalloc for memory profiling in a python code. I'm having difficulty tracing back to my python function calls. 

When analyzing the heap profile generated by jemalloc, it only shows C API calls related to the Python interpreter, but does not show my actual python function that is responsible for memory allocation.

```
user@user:~/Documents/jemalloc/python_jemalloc$ jeprof /usr/bin/python3 jeprof.out.28677.1.i1.heap
Using local file /usr/bin/python3.
Using local file jeprof.out.28677.1.i1.heap.
Welcome to jeprof!  For help, type 'help'.
(jeprof) top
Total: 63.4 MB
    63.4 100.0% 100.0%     63.4 100.0% prof_backtrace_impl
     0.0   0.0% 100.0%      0.5   0.9% GLIBC_2.2.5
     0.0   0.0% 100.0%      1.1   1.7% PyCFunction_Call
     0.0   0.0% 100.0%      0.6   0.9% PyConfig_Clear
     0.0   0.0% 100.0%      0.6   0.9% PyDict_ClearFreeList
     0.0   0.0% 100.0%      0.6   0.9% PyDict_SetDefault
     0.0   0.0% 100.0%     62.4  98.3% PyEval_EvalCode
     0.0   0.0% 100.0%      1.1   1.7% PyImport_Import
     0.0   0.0% 100.0%      1.1   1.7% PyImport_ImportModule
     0.0   0.0% 100.0%      1.1   1.7% PyImport_ImportModuleLevelObject
```

I would like to know if there is any way around this to achieve the python function that is responsible for memory allocation.

**Comment by interwq** [comment]
>  I'm having difficulty tracing back to my python function calls.

This isn't currently possible with the default stack unwinder, which would need to backtraces python functions that is not trivial. This is more of a feature for the unwinder though, as jemalloc simply logs the output from the unwinder.

For the context, there are a few profiling hooks offered by jemalloc, in order to facilitate the implementation of unwinding python stacks. cc: @AlbertDachiChen in case there's plan to open source that part of the tool.

**Comment by rynewang** [comment]
Any updates on this?

**Comment by snakethatlovesstaticlibs** [comment]
+1 this would be a very powerful usecase
