### ISSUE TITLE
Does jemalloc support jni?

### ISSUE THREAD

**Issue by pineking** [jemalloc/jemalloc#247]
my code is written using C/C++ with jemalloc, and JNI is used to call  C/C++ code from java.

Does jemalloc work fine with jvm? or crash the jvm? 

I have used tcmalloc, which will cause the crash together with jni.

**Comment by jasone** [comment]
You cannot safely use jemalloc as a generic malloc replacement within a dynamically loadable module, because the main application and the module will mix up which allocator to free objects to.  The only way to make jemalloc work with your loadable module is to build the entire Java runtime with jemalloc as the allocator, so that *all* code uses jemalloc for allocation.
