### ISSUE TITLE
Decommit unused trailing pages in huge allocations

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#252]
Some of the smallest  huge size classes are not perfect multiples of the chunk size, and the unused trailing pages can be decommitted.  Extent nodes will need to somehow encode whether the unused trailing pages are decommitted, perhaps by overloading the meaning of the "decommitted" attribute for extant huge allocations to apply only to the unused trailing pages, much like the "zeroed" attribute.

**Comment by glandium** [comment]
By the way, today I was hitting an interesting Firefox test failure which ended being caused by the change of huge size classes compared to mozjemalloc, combined with the test itself doing something stupid. But I do wonder if jemalloc is not being a little wasteful. In my case, an allocation slightly above 128MB ended up mapping 160MB with jemalloc instead of 129M with mozjemalloc. That's quite a big amount of wasted address space...

**Comment by jasone** [comment]
This will likely be a natural consequence of #360, so I'm pushing the milestone to 5.0.0.

**Comment by jasone** [comment]
This went away as a side effect of removing chunks in #360.
