### ISSUE TITLE
Extend chunk hooks to be object-oriented.

### ISSUE THREAD

**Issue by ldalessa** [jemalloc/jemalloc#259]
Now that the `chunk_hooks_t` "class" exists, it would be useful to extend the member functions to be object-oriented, rather than static (in the sense of C++ members). This would just require extending the member types to take one more paramter, the `chunk_hooks_t` pointer, and that the `chunk_hooks_t` be passed back into the member functions when they need to be called. Right now we have some awkward `static` objects and replicated handlers to deal with this lack.

**Comment by jasone** [comment]
I considered whether to add an opaque data pointer before the introduction of ```chunk_hooks_t```, but settled on making ```arena_ind``` the key on which to base look-aside  for chunk allocator metadata.  The reasons for this include:

1) It fits well with jemalloc's internal chunk allocator infrastructure.
2) Back when there were multiple mallctl interfaces (chunk alloc/dalloc/purge), this would have required yet another mallctl interface.
3) In practice, since arena indices are inherently globally unique, ```arena_ind``` feels conceptually similar, even though it requires that ```arena_ind``` be used as a lookup key for some applications.

It's too bad we didn't revisit this before the 4.0.0 release, because changing chunk_hooks_t breaks the ABI, and we can't do that until 5.0.0.  In retrospect, this would have simplified some code in jemalloc's internal chunk allocator functions, e.g. https://github.com/jemalloc/jemalloc/blob/4.0.0/src/chunk.c#L422.

**Comment by ldalessa** [comment]
Yeah, it's too bad I didn'tr try and upgrade our infrastructure before 4.0.0. 2) was the reason I never suggested it before, and I didn't realize the hooks structure had arrived until too late.

I hadn't considered it, but the `arena_ind` is probably something I can work with as long as I don't mind burning a bit of space or know the offset of the first extended arena. That should actually let me eliminate some redundancy even if it is a bit more cumbersome than the instance pointer.

Thanks.
