### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jacheut** [jemalloc/jemalloc#2604]
It's been a long time since a new version was released. Can release a new version?

**Comment by interwq** [comment]
No new release is planned in the near future. There are quite some development ongoing (e.g. around huge pages), but these may take a while to finish and fine tune. If you'd like to try the most recent versions, #2060 contains pointers to the production-tested commits.

Note that the release frequency is lower since 5.0, mainly as a result of the improved CI coverage. This was called out in the 5.0 release note:
https://github.com/jemalloc/jemalloc/releases/tag/5.0.0

**Comment by marlon-sousa** [comment]
Hello,

Can you confirm that the last stable release is 5.3.0? Asking to double check because by outside looking it seemed that somehow tags just stopped being generated, as if release management had turned to something else.

I just need to build jemalloc from source and wanted to pick the last considered stable release to make builds reproducible.

BTW: I have looked into documentation, but thought it would be better just to double check.

Thamks,
Marlon

**Comment by guangli-dai** [comment]
Yes, [this](https://github.com/jemalloc/jemalloc/releases/tag/5.3.0) is the latest stable release.

**Comment by marlon-sousa** [comment]
Thamks for replying.

I cannot close this issue, but as far as I am concerned it can be closed.

**Comment by raboof** [comment]
> I just need to build jemalloc from source and wanted to pick the last considered stable release to make builds reproducible.

Do you mean bit-by-bit reproducibility? Did that work for you on 5.3.0? We've been running into issues with that in nixpkgs (https://github.com/NixOS/nixpkgs/issues/380852).
