### ISSUE TITLE
Segmentation fault when hiding symbols of my shared library (.so)

### ISSUE THREAD

**Issue by JonathanGirardeau** [jemalloc/jemalloc#2660]
Hello,

I build a shared library that is linked statically to `libjemalloc_pic.a`.
I use the `--disable-initial-exec-tls` option because I want my library to be loadable dynamically (with dlopen).

When I create an executable that is linked to my shared library, it works.
As soon as I hide symbols of my shared library, I get segmentation fault. I got the same result when trying to load my shared library at startup or after startup (with dlopen).

When I try to remove jemalloc and hide symbols, it works.

I guess I need to export some symbols of jemalloc. I have tried to export this list but it does not fix the problem:
```
malloc;
calloc;
posix_memalign;
aligned_alloc;
realloc;
free;
malloc_usable_size;
memalign;
pvalloc;
valloc;
```

**Comment by interwq** [comment]
The segfault likely comes from mixed allocator usage, e.g. allocate from one but free to another one.

Unfortunately I don't think there's perfect solution for the combination here, either we should 1) make sure there's only 1 allocator impl for the entire process, or 2) make sure there's no cross allocator boundary activities. Also for the dlopen lib case, consider using jemalloc with a prefix (instead of replacing the default malloc symbols), and explicitly use jemalloc for the call sites that matters and are safe.

**Comment by JonathanGirardeau** [comment]
Thanks for your answer.
I understand that the use of dlopen would have good chance to mix allocator usage. That is why you advise me to use jemalloc with a prefix, however I wanted to use jemalloc implicitely so it does not change my code.
I think I will try to inject jemalloc into the application at run time with `LD_PRELOAD`, it should prevent form mixing allocator, what do you think ?

**Comment by interwq** [comment]
Yes LD_PRELOAD is safe and the recommended way
