### ISSUE TITLE
Is library still supported

### ISSUE THREAD

**Issue by rodgreennc** [jemalloc/jemalloc#2666]
There hasn't been a new release in 2 years, and the last issue was a year ago. Is the library still actively supported?

Since there hasn't been a release in 2 years, my company is concerned that the library might have been, as they phrase it, "abandoned". I think a primary concern is that if there were to be a security vulnerability identified, that there would be developers looking at it.

**Comment by interwq** [comment]
No notable bugs or security issues we are aware of. If there were any, we would have bugfix releases to cover them.

Also copy-paste from another thread:

No new release is planned in the near future. There are quite some development ongoing (e.g. around huge pages), but these may take a while to finish and fine tune. If you'd like to try the most recent versions, https://github.com/jemalloc/jemalloc/issues/2060 contains pointers to the production-tested commits.

Note that the release frequency is lower since 5.0, mainly as a result of the improved CI coverage. This was called out in the 5.0 release note:
https://github.com/jemalloc/jemalloc/releases/tag/5.0.0
