### ISSUE TITLE
Chunk hooks should be inherited from arena[0] ?

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#270]
If an arena is created manually, it will currently get the default hooks. However, at least in my case, the chunk hooks I'm setting up at startup time are meant to be used by all arenas, however they are being created. I /think/ it would make sense for arenas to inherit chunk hooks from arena[0] when they are created, but I'm not sure if it's a sane default for every use and should be optional as such.

**Comment by ldalessa** [comment]
We don't have that pattern at all. Though we don't reset the default arena hooks ever because a) we don't need to and b) it seems to be unsafe since we can't prevent initial chunk allocation with the default hooks.

Though the b) constraint may have evolved since I wrote that code originally.

**Comment by jasone** [comment]
Most of the use cases I've imagined involve custom chunk hooks for arenas created via the "arenas.extend" mallctl.  One possibility for your use case would be to just iterate over all "opt.narenas" and set the chunk hooks.  Unfortunately, I can't think of a simple way to trigger arena initialization other than allocating memory, and the "arena.<i>.chunk_hooks" mallctl doesn't currently trigger arena initialization as a side effect.  We'd need a mechanism to trigger cheap (no-allocation) arena initialization for the iteration approach to work well.

**Comment by glandium** [comment]
I'm already iterating over `narenas`, although since I only have one, I don't know if I'd be missing out on initialization. But my concern, and the reason I opened this issue, is that currently, arenas created with arenas.extend *do* need an additional *manual* setting of chunk_hooks, which is administrative trivia that shouldn't be handled by the caller of arenas.extend. I guess I could wrap the whole thing...

**Comment by ronawho** [comment]
I saw this thread and wanted to note what we do in case it's useful to others:

>Unfortunately, I can't think of a simple way to trigger arena initialization
other than allocating memory... We'd need a mechanism to trigger cheap
(no-allocation) arena initialization for the iteration approach to work well.

For some configurations, we replace the chunk hooks for every arena. We
initialize them by looping over the arenas and setting the current thread to
use it with the [thread.arena](http://www.canonware.com/download/jemalloc/jemalloc-latest/doc/jemalloc.html#thread.arena) mallctl. The code looks something like:

```c
  // for each non-zero arena, set the current thread to use it (this
  // initializes each arena). arena 0 is automatically initialized.
  //
  //   jemalloc 4.0.4 man: "If the specified arena was not initialized
  //   beforehand, it will be automatically initialized as a side effect of
  //   calling this interface."
  for (arena=1; arena<narenas; arena++) {
    je_mallctl("thread.arena", NULL, NULL, &arena, sizeof(arena))
  }

  // then set the current thread back to using arena 0
  arena = 0;
  je_mallctl("thread.arena", NULL, NULL, &arena, sizeof(arena))
```

I haven't explicitly timed this code, but it seems to work pretty fast. We have
a performance test that checks startup time, and it only increased at most
~.002 seconds on a machine with 48 HT (192 arenas.)

For context: In order to support fast 1-sided communication, some of our
communication layers want our entire heap to be registered with the NIC. To do
this with jemalloc we basically grab a huge chunk of memory from the system and
register it with the NIC. We then initialize the arenas, change the chunk hooks
for each arena to allocate out of this registered memory, and finally we waste
whatever memory arena 0 got from the system before we had a chance to replace
the chunk hooks.

**Comment by jasone** [comment]
Ah, nice, @ronawho.
