### ISSUE TITLE
`je_cv_madv_free=no` no longer overrides `MADV_FREE` when building for Linux

### ISSUE THREAD

**Issue by StephenWakely** [jemalloc/jemalloc#2728]
A number of projects have found using `madvise` with `MADV_FREE` to be problematic. [example](https://github.com/cockroachdb/cockroach/issues/83790).

So they use:

```
echo "je_cv_madv_free=no" > config.cache && ./configure -C
```

as mentioned in the [docs](https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md)

This no longer works since [this PR](https://github.com/jemalloc/jemalloc/pull/1048) changed things. Now when you are building for Linux you always get `JEMALLOC_PURGE_MADVISE_FREE` defined which results in `MADV_FREE` being used.

I realise the intent of this flag is to just turn this off for systems that don't support it, but given that folks do use it because they would like it off even in systems that do support `MADV_FREE`, would it be possible to create a way to do this for all systems?

**Comment by interwq** [comment]
@StephenWakely thanks for sharing the findings. Indeed we switched to runtime detection for MADV_FREE so that example in the doc isn't valid anymore.

We also found the not-updating-RSS aspect of MADV_FREE being an issue, and disabled it by default in https://github.com/jemalloc/jemalloc/pull/1421 (included in releases since 5.2.0)

I'd suggest trying the current release 5.3. With pre-5.2 versions, you can disable it using the [muzzy_decay_ms option](https://jemalloc.net/jemalloc.3.html#opt.muzzy_decay_ms), e.g. configure jemalloc with `--with-malloc-conf=muzzy_decay_ms:0`

**Comment by StephenWakely** [comment]
Ah. Amazing! I am already with 5.3 and wasn't experiencing any issues, but just wanted to disable it *just in case*. So it's great to hear I don't need to do anything.

Many thanks for your help!

**Comment by interwq** [comment]
Also updated the config cache example in INSTALL: https://github.com/jemalloc/jemalloc/pull/2731

Thanks again @StephenWakely
