### ISSUE TITLE
jemalloc is ~20% slower than tcmalloc on ppc64el architecture

### ISSUE THREAD

**Issue by leitao** [jemalloc/jemalloc#279]
Running a quite simple test, it was shown that jemalloc is slower than tcmalloc on PPC64LE architecture.

One of the benchmarks used is https://github.com/leitao/malloc_benchmark

This bug is being opened to track the performance improvement on the POWER architecture.

**Comment by thestinger** [comment]
I would expect it to lose to TCMalloc on most small scale tests because it doesn't allow thread caches to grow to massive sizes and the red-black tree wrangling is expensive. It could offer the option of using a faster O(1) slab allocation mechanism for very small allocations by segregating the chunks from the ones used for larger allocations... would need to give up on packing them towards low addresses though (just LIFO list of slabs, with either a bitmap or LIFO list inside each one). Not sure it'd be a good fit with jemalloc's goals.

**Comment by thestinger** [comment]
The current bitmap-based scheme packs data much better than slab allocation would too, since it's not segregated per-size-class but rather per-spacing-class. Maybe there's some happy medium between them.

**Comment by jasone** [comment]
A link to a microbenchmark as a distinct issue isn't very useful for performance tracking.  If you think the microbenchmark may be informative for existing optimization issues (e.g. #148), please comment on those issues, or suggest/develop other optimizations that may improve general performance.
