### ISSUE TITLE
memory leak of 4MB on dlopen/dlclose

### ISSUE THREAD

**Issue by gklingler** [jemalloc/jemalloc#288]
dlopen/dlclose of a shared library that uses jemalloc leaks 4096kb of virtual memory.
See demo - a small example program that shows the effect: https://drive.google.com/file/d/0BwgGEO6-4LMXcmk5VEJjU1V5cHc/view?usp=sharing

The output of the demo:
```
initial  : vm: 14728, rss: 1412   [kb]

opening dl ... 
StaticClass() - allocating memory
dl opened: vm: 25308, rss: 3104   [kb]

closing dl ... 
~StaticClass() - freeing memory
dl closed: vm: 20992, rss: 2888   [kb]

opening dl ... 
StaticClass() - allocating memory
dl opened: vm: 29404, rss: 3148   [kb]

closing dl ... 
~StaticClass() - freeing memory
dl closed: vm: 25088, rss: 2932   [kb]
```

=> virtual memory difference between first and second dlclose: 25088-20992 = 4096
This looks like a bug.

Ubuntu 14.04, jemalloc-4.0.3 with default configuration flags.

**Comment by jasone** [comment]
This is intentionally not a supported use case.  There are no mechanisms for iterating over internal nor application allocations, and such mechanisms would be a substantial burden for questionable practical benefit.  It's dangerous to dlopen() a library that uses jemalloc unless you mangle the jemalloc API so that there's no risk of mixed allocator usage (e.g. malloc() with the system allocator and free() with jemalloc).  Furthermore, if jemalloc were modified to avoid the "leak", then the application would also have to assure that no jemalloc-allocated memory were touched after dlclose().
