### ISSUE TITLE
canonware.com is down

### ISSUE THREAD

**Issue by mr-salty** [jemalloc/jemalloc#309]
When I visit canonware.com I see "This domain name has been registered with Gandi.net / It is currently being parked by the owner".   Hope all is well and the site will be back soon.

https://github.com/treasure-data/omnibus-td-agent/blob/master/config/software/jemalloc.rb tries to download tar files from canonware.com although I can work around it so it's not urgent.

**Comment by mr-salty** [comment]
appears to be fixed now.

**Comment by jasone** [comment]
This is due to a domain name transfer from Network Solutions to Gandi, which completed two days earlier than expected.  Unfortunately, the TTL was still set high (24+ hours?), so not all DNS caches have expired yet.  In your case, you only experienced the 3 hour TTL of the zone file being served by Gandi when the transfer first completed.
