### ISSUE TITLE
thread caches are only ever half full

### ISSUE THREAD

**Issue by buchgr** [jemalloc/jemalloc#322]
The thread caches only ever seem to be filled at most 50%. The problem appears to be this logic https://github.com/jemalloc/jemalloc/blob/dev/src/arena.c#L1981 in `arena_tcache_fill_small`. 

Basically `tbin->lg_fill_div` is always greater than 0 and so `nfill` is at most `ncached_max >> 1`. The consequence is that entries `[ncached_max/2, ncached)` in `tbin->avail` are always `null` and never used in the tcache allocation logic.

I have a PR ready to fix this, if there is agreement that this an issue @jasone.

Thanks.

**Comment by jasone** [comment]
IIRC, the intention is for ```nfill``` to never be larger than half the available space.  This is a hysteresis mechanism.  If we completely filled the slots during a fill, then we'd be in danger of having to spill after only two deallocations.

**Comment by buchgr** [comment]
> If we completely filled the slots during a fill, then we'd be in danger of having to spill after only two deallocations.

Yes, because of the check `if (unlikely(tbin->ncached == tbin_info->ncached_max))` in `tcache_dalloc_small` right? What I am trying to say is that this condition is essentially dead code, as `tbin->ncached` is at most ever `tbin_info->ncached_max / 2`.

It seems to me that we would want to initially fill the cache to e.g. `ncached_max / 2`, but as we require more space, we eventually also want to fill the cache to `ncached_max`?

**Comment by jasone** [comment]
We do fill the cache to ```ncache_max``` if a series of ```tcache_dalloc_{small,large}()``` calls occur in succession.  If the cache is full and we try to deallocate yet another object, we first flush half the cache in order to make room for more deallocations, but we leave half the cache so that if the flush is immediately followed by multiple allocation requests, we don't have to immediately fill again.

The cache fill/spill operations only fill/spill half the cache at a time so that even in the worst case we only do a spill/fill once every ```ncached_max / 2``` [de]allocation operations.

**Comment by buchgr** [comment]
ahh I am stupid ... you are right :-). sorry about that!
