### ISSUE TITLE
Add option to only have a single chunk cache

### ISSUE THREAD

**Issue by cferris1000** [jemalloc/jemalloc#350]
Each arena has its own huge chunk cache, but on 32 bit systems, there isn't a lot of virtual address space available. With these multiple chunk caches, and a program that creates a thread and does a huge allocation, eventually, the entire virtual address space can be exhausted. It is especially bad if a thread is created which does a single really big allocation.

It would be useful to have some kind of option to allow the use of a single chunk cache for these cases.

**Comment by jasone** [comment]
There are currently two ways I can think of to deal with this, ```narenas:1``` (has the side effect of only one cache) and ```--enable-munmap``` (limits how much virtual memory is cached).  In fact, maybe it makes sense to stop implying ```--disable-munmap``` on 32-bit Linux.  What do you think of these as possible solutions?

**Comment by cferris1000** [comment]
I tried using the munmap option but it wound up killing performance. I'll try this again with the decay based purge mechanism. I suspect that will make the munmap less bad.

**Comment by jasone** [comment]
Note that as of 4.0.0, chunks were integrated into the unused dirty page LRUs (ee41ad409a43d12900a5a3108f6c14f84e4eb0eb), so if you tried ```--enable-munmap``` with 3.x, that should help too.

**Comment by jasone** [comment]
I've been contemplating the design and implications of centralized retained memory, as compared to the current system as it exists on the dev branch, where each arena retains memory independently.  More specifically, when an extent is logically deallocated, cleanup attempts cascade from deallocate-->decommit-->lazy purge-->forced purge.  Memory is retained if the deallocation attempt fails; the rest of the cascade merely decreases the RSS cost of retained memory.

We need to continue allowing arenas with custom extent hooks to use the built-in per arena retained memory infrastructure.  If we offer centralized retained memory, it needs to apply only to automatically managed arenas, because otherwise we can't safely/cleanly support arena destruction.

If we implement centralized retained memory, the coalescing logic will need a slight adjustment; currently it refuses to coalesce extents that originated from distinct arenas.

We currently have efforts under way (#14) to reduce the default number of arenas to the number of CPUs, which is a 4X reduction from current behavior.  We will also improve large allocation scalability (#466, incidentally requires refactoring that makes #350 easier), which was the prohibitive bottleneck in my previous experiments with single-arena configurations.  Might we determine that using a single arena on 32-bit systems is a reasonable solution?  I have a preference for automatic solutions, so I'd prefer defaulting to centralized retained memory on 32-bit systems and leaving automatic arena configuration dependent only on the number of CPUs.  The bummer though is that we introduce yet another configuration knob as part of this solution.

Thoughts?

**Comment by jasone** [comment]
The only option I'm comfortable with right now beyond the existing enhancements such as #14 and #521 is to enable munmap on 32-bit Linux systems by default, so that we don't retain virtual memory on a per arena basis.  I'm going to put together a diff for that, and then close this issue unless people have additional options they want to discuss.
