### ISSUE TITLE
Misleading Leak Summary and Final Memory Usage in Java/Jetty Web Application 

### ISSUE THREAD

**Issue by kodeva** [jemalloc/jemalloc#356]
Hi.
I am trying to find a source of memory leak (in non java heap) in our Java application (in Jetty) using jemalloc. I am running Java with following settings, where the jemalloc version is 4.0.4:
> export JEMALLOC_PATH="/usr/local"
> export LD_PRELOAD="$JEMALLOC_PATH/lib/libjemalloc.so"
> export MALLOC_CONF="prof:true,lg_prof_interval:30,lg_prof_sample:17,prof_leak:true,prof_final:true"

After a start and stop of the application I can see a message similar to the following:
> jemalloc: Leak summary: 40202720 bytes, 1409 objects, 104 contexts
> jemalloc: Run jeprof on "jeprof.37510.10.f.heap" for leak detail

The issues is that the numbers in leak summary are always different - from approx. 200 MB to 400 MB. And output of `jeprof --text /usr/bin/java jeprof.37510.10.f.heap` is different as well - structure similar, but numbers different. Moreover the numbers in the jeprof output are completely different from the leak summary.

It seems to me that some cleanup in Java is still not finished at the time when the leak summary and final heap memory usage are being taken. How can I assure that jemalloc leak summary and final memory usage dump operation are executed only after in Java process (all its threads) end?

Thank you,
Stepan.

**Comment by jasone** [comment]
The leak report is generated via an ```atexit()```-registered function, but it's possible that other applications threads continue to concurrently execute, plus there may be other ```atexit()```-registered functions that execute after the leak report is generated.  If you can quiesce the application prior to exit, that will at least solve the concurrent execution issue.

```lg_prof_sample:17``` means that not all allocations are sampled, and the leak summary only reports sampled allocations, whereas ```jeprof``` reports the expected number of leaked allocations based on the sample set.  This inconsistency is fixable via a bit of extra math, though I've been contemplating removing the leak report code altogether since it became extremely expensive to sample all allocations (```lg_prof_sample:0```) as a side effect of some optimization/simplification work between 3.6.0 and 4.0.0.  Better might be to implement the necessary math to scale the sample size up to the expected leak size for consistency with ```jeprof```.
