### ISSUE TITLE
Use MADV_FREE on linux kernel >= 4.5

### ISSUE THREAD

**Issue by rajatgoel** [jemalloc/jemalloc#387]
Maybe a new configure option to enable/disable this at compile time for linux?

**Comment by djwatson** [comment]
Last I tested MADV_FREE doesn't work correctly on swapless systems yet (changes still in review -https://lkml.org/lkml/2015/11/24/753).  So probably can't be be the default yet and needs to be an option

**Comment by jasone** [comment]
It looks like the current state of affairs is that ```MADV_FREE``` is equivalent to ```MADV_DONTNEED``` on swapless systems, so I think it's okay to use, even if currently a minor pessimization since we won't recognized the pages as being zeroed upon reuse.

**Comment by madscientist** [comment]
Maybe it's just me but I'm leery of configure-time checks for things like this.  What happens if I build this on a system where it's available but then run it on a system where it isn't?  Maybe this is a spurious concern.

**Comment by jasone** [comment]
Yeah, cross compiling of any form is in general a dangerous business, and this particular configuration test is a bit more fragile than most because we tend to think of systems with merely different kernel versions as equivalent targets.  That said, I want to support ```MADV_FREE``` on Linux, but I don't want to saddle us with a compatibility quagmire or explicit configuration control.  What we have here is a forward-compatible approach, with an escape hatch (```--config``` autoconf cache file) to enable backward compatibility for people who are actually cross-compiling from newer systems to older ones.

**Comment by nh2** [comment]
> It looks like the current state of affairs is that `MADV_FREE` is equivalent to `MADV_DONTNEED` on swapless systems

@jasone @djwatson This is no longer the case, see

https://www.spinics.net/lists/linux-mm/msg167333.html

`MADV_FREE` now always returns memory to the operating systems "lazily" (on memory pressure).
