### ISSUE TITLE
Delphi and jemalloc allocator leaks memory

### ISSUE THREAD

**Issue by dejancrn** [jemalloc/jemalloc#416]
We have an application written in Delphi which is heavily multithreaded and are intersting in replacing default FastMM4 allocator which is not good for multithreading environment. 

We have succeeded in replacing the allocator but we are seeing that memory is constantly growing and therefore assume that jemalloc is leaking. We tried the same application/test also with FastMM4/TCMalloc/msvcrt allocators and there it does not leak. jemalloc has been compiled with Visual Studio 2015 and also with Mingw w64 and both have the same effect.

Are there any known issues which would produce such leak? We are only using je_malloc, je_free, je_calloc and je_realloc functions.

**Comment by djwatson** [comment]
Can you provide jemalloc stats dump, using malloc_stats_print or malloc_conf option?

**Comment by dejancrn** [comment]
[stats.zip](https://github.com/jemalloc/jemalloc/files/343049/stats.zip)

**Comment by jasone** [comment]
There are underflowing ```allocated``` and ```curhchunks``` stats for several huge size classes, which may be due to a jemalloc bug, or due to an application bug (double frees).  If it is an application bug, you can increase the likelihood of catching it by using a debug build of jemalloc.  Also, you can test with a larger chunk size (e.g. 2^21 rather than 2^16), which will change which code paths are executed for these underflowing stats and potentially trigger other assertions.

Aside from those underflowing stats, I don't see anything out of the ordinary that could explain unbounded memory usage growth.

**Comment by dejancrn** [comment]
i tried it again with lg_chunk:21 and it seems that only huge buffers seem to have problem. See attached file. I also tried with debug version and ran debug from VS but no assertions were triggered.

I think it's not application bug because other managers i tried are working ok and with FastMM4 memory manager we have memory issue detector (double frees, leaks, ...).

We would really like to use Jemalloc because from performance point of view it seems the fastest.

[stats1.zip](https://github.com/jemalloc/jemalloc/files/353950/stats1.zip)

**Comment by jasone** [comment]
@dejancrn, multiple virtual memory leaks were fixed between 4.2.1 and 4.3.1, so you are likely to see better results than when you first reported this issue.

**Comment by jasone** [comment]
This was very likely the same issue as #487.  I'm going to close this as a duplicate, but if you continue to observe this problem with 4.3.1, please re-open with additional info so we can resolve the underlying cause.
