### ISSUE TITLE
Compiled-in page size makes jemalloc binaries unportable

### ISSUE THREAD

**Issue by cuviper** [jemalloc/jemalloc#467]
I see that configure uses `sysconf(_SC_PAGESIZE)` at compile time to determine the page size.  However, this can vary depending on kernel configuration, so a jemalloc compiled on one machine may have issues running on some other machine.  For instance, Debian aarch64 uses 4k pages, but Fedora uses 64k, so a Debian jemalloc effectively can't run correctly on Fedora.

The concrete issue I encountered was in trying to bootstrap Rust aarch64 on Fedora.  Because Rust is self-hosting, I have to use upstream binaries to get started.  I was getting strange crashes, and when I tried strace I saw this:

```
2 madvise(0x3ff7a398000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7a3cd000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7a465000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7970b000, 65536, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7a6d6000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7a7aa000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7a7e0000, 8192, MADV_DONTNEED) = 0
2 madvise(0x3ff7a927000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7aab0000, 8192, MADV_DONTNEED) = 0
2 madvise(0x3ff79659000, 86016, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7aacf000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff778ae000, 28672, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7ad07000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7aeb7000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff7b0c2000, 8192, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 madvise(0x3ff779ba000, 200704, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
2 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
```

So it seems clearly expecting to have 4k pages.  Most of the `madvise` calls were not on the real 64k page boundaries, so they get `EINVAL`.  A few of them happen to align, so they succeed -- but the requested length was less than 64k and the kernel _rounds up_!  Thus it will dump more memory than intended, and I suspect the SEGV addr=0x8 is a deref of a nulled-pointer from the cleared page.

I have managed to get around this with: `export MALLOC_CONF=lg_dirty_mult:-1`.  But I think it would be better if jemalloc read the page size at runtime, and FWIW Firefox's forked "mozjemalloc" does exactly that.

**Comment by jasone** [comment]
You can use e.g. ```--with-lg-page=16``` to cross-compile to a target that uses 64 KiB pages.  jemalloc used to check page size during bootstrapping, but this had two shortcomings.  First, it was difficult to avoid recursive allocation on all platforms, and second, making the page size dynamic prevented some compiler optimizations.  IIRC Solaris is the only platform I could find on which it was conceivable for a single system to use multiple page sizes (thus warranting a run-time check), but even there it was not a practical concern.

**Comment by cuviper** [comment]
I think in this case, Rust would like to have binaries that run *everywhere*, not subject to the configuration whims of different distros.  So `--with-lg-page=16` just makes a different non-portable binary, rather than something universal.

Is it feasible to run jemalloc compiled with the 64k page size even on systems that are only 4k?  I guess these `madvise` calls would be fine, but general `mmap` will probably be surprising if it returns address aligned less than expected.  And Mozilla [bug 1091515](https://bugzilla.mozilla.org/show_bug.cgi?id=1091515) showed real problems with `munmap` (on mozjemalloc).

I'm not surprised that dynamic page size reduces compiler optimizations.  Perhaps some of that can be mitigated with different expressions, e.g. instead of page mask, use a shr+shl combo to strip bits.  But I'm sure that's a lot of code to deal with.

FWIW a single system *could* have different page sizes with different kernels -- e.g. a kernel developer who normally runs the distro kernel, but sometimes reboots into their own build.  Obviously they would not want to swap out all userspace each time.  But maybe mixed pages are impractical for other reasons.  There may be other programs with static page sizes too, and that's normally just fine in a controlled distro.

**Comment by jasone** [comment]
Earlier this year I tried making it possible to specify a larger page size than the true system page size (245ae6036c09cc11a72fab4335495d95cddd5beb), but I had to revert it (05a9e4ac651eb0c728e83fd883425c4894a2ae2b) because it could cause VM map fragmentation.

**Comment by cuviper** [comment]
What about `--with-lg-page-sizes`?  That sounds like it's supposed to support a hybrid configuration.

**Comment by jasone** [comment]
```--with-lg-page-sizes``` is only useful when generating headers that will be imported into another build system that doesn't run configure again, e.g. in FreeBSD's libc, which in turn can be built for a variety of architectures.

**Comment by glandium** [comment]
More than a cross-distro problem, it can cause problems in a single distro, where the user switches the page size it their kernel.

Now, something that /could/ work, is if one configured --with-lg-pages for the biggest you can expect a kernel to use. The problem is that it then brakes `chunk_alloc_mmap_slow` when the runtime page size is actually smaller, and you end up with chunks actually smaller than the chunk size. Fun ensues.

**Comment by joshlf** [comment]
How expensive would it be (in code bloat, etc) to have multiple copies of the code compiled for different constants (to still get the benefit of compiler optimizations which are aware of the page size)? So you basically compile three different versions of the code - the 4K page version, the 64K page version, and, if you're being really careful, the X page version (where X must be determined at runtime). Then, at init time when a process starts, you decide which one you're going to use.

**Comment by jasone** [comment]
Page size is baked into various data structures at compile time, so we would have to make substantial changes to directly support multiple page sizes at run time.  However, it is possible to support a system page size smaller than the page size that is baked in.  #769 implements such support.

**Comment by cuviper** [comment]
Nice!

**Comment by xidiandb** [comment]
Can't fit 4K and 64K kernel at the same time？ @jasone

**Comment by pmarreck** [comment]
I've spent the last hour+ or so reading up on this issue, and `jemalloc`'s insistence on taking advantage of compile time optimizations by baking in static page size seems to be the reason for a lot of ARM software incompatibility out there on Linux currently.

My uninvited opinion as a 20+ year software developer is that ARM CPU's are just going to become more prevalent and since various ARM flavors (apple's is 16k by default but the OS supports up to 64k I believe with any option supported at runtime) and Linux versions running on them (NixOS, Asahi, numerous others) will likely be built across a variety of page sizes, and with projects like Asahi Linux to bring Linux to Apple's hardware wanting 16k support, the only thing that makes sense to me is to give up the compile-time optimizations you get with a static page size and just support runtime page size configuration depending on the state of the OS at runtime. This also has the nice side effect of making binaries more portable for x86_64 as well, if that is the compilation target.

**Comment by gewalker** [comment]
> I've spent the last hour+ or so reading up on this issue, and `jemalloc`'s insistence on taking advantage of compile time optimizations by baking in static page size seems to be the reason for a lot of ARM software incompatibility out there on Linux currently.

The upside of open source software is that it scratches a lot of itches.  The downside is that sometimes a project is run by person or persons who don't share your itch.  People get mired in their platform and their optimizations.  It's sadly typical, and I hope they decide to get with the present at some point because there's very little more useless than falling in love with your own performance solution.

**Comment by C0rn3j** [comment]
First off, thanks to @jasone for striving to arrive at a reasonable fix for this over the years. 

> making the page size dynamic prevented some compiler optimizations

Since upstreams that link this issue all decide to solve(or in some cases, not solve) the problem their own way, we've now reached a state where on some devices*, to maintain the ability to be able to use desired software, one needs to disable optimizations for the hardware and trade them for optimizations in jemalloc.

What is the performance gain those optimizations provide that would be lost by making the page size dynamic in jemalloc?

\* *For example the RPi 5, where its firmware by default loads the hardware-optimized kernel with 16k pages*

**Comment by marcan** [comment]
Another downstream project that refuses to support *architecturally required* page sizes on ARM64 because jemalloc won't on its default config: https://github.com/telegramdesktop/tdesktop/issues/26710 (and then [we get the bug reports](https://www.reddit.com/r/AsahiLinux/comments/1c34b87/telegram_stopped_working/)). Just look at the mentions on this issue and you'll see how many projects are hitting this problem.

This is kind of ridiculous at this point. If jemalloc does not change its build-time default to 64K (on ARM64) or implements dynamic page sizes in some fashion, it is actively choosing to sabotage the ARM64 Linux ecosystem. It is *not* optional to support other page sizes on software that is intended to actually work on all devices. This isn't about just Macs any more, the Rasperry Pi 5 also uses 16K pages. It is ridiculous that we have to ask every single downstream project to use non-default build options to produce correct, portable binaries just because jemalloc chooses not to have sane defaults.

Seriously, we're tired of jemalloc errors all over the place. It's not reasonable to expect everyone to override build defaults. Please fix this. If someone wants to take advantage of the performance benefits of using a 4K build on 4K machines, *they* have to make that choice. The defaults should actually work everywhere.

**Comment by gewalker** [comment]
Agreed, delta “kind of”. I ran into this years ago, had to go a different
route because of it and have entirely forgotten what project that was for
at this point.

Gary E. Walker
email/gtalk: ***@***.*** | twitter: @gewalker
The universe is expanding because it's trying to get away from the Internet.
PGP public key: https://gewalker.net/files/pubkey.asc

**Comment by devnoname120** [comment]
> it is actively choosing to sabotage the ARM64 Linux ecosystem

@marcan IMO this comment is abusive. As much as I like your work (I even sponsor you), I don't think it's OK to insinuate malevolence.

**Comment by dzaima** [comment]
As far as I understand, on ARM, assuming the compile-time page size is equivalent to the runtime one is exactly as non-portable as doing `-march=native`.

That is to say, in any scenario where a non-64K page size is hard-coded, architecturally speaking, `-march=native` is completely safe to add. So here's a free potential perf boost to add in the default jemalloc aarch64 linux configuration that does not add any additional portability concerns - compile with `-march=native` :) <sub>(might be slightly less trivial if you wanted nice error messages on mismatched compile-time vs runtime arch; and on aarch64 the difference between native and baseline isn't that large; but this is for making a point rather than being a serious suggestion ¯\\\_(ツ)\_/¯)</sub>

I might not quite call this active sabotage, but it's a pretty simple fact that essentially doing `-march=native` on a single architecture while not having equivalent behavior on others is a rather unusual stance for the default configuration.

**Comment by Kamayuq** [comment]
I can understand the compiler optimization. But the pagesize is always a pow2 so you just do the masking for div/mod manually as the compiler would. (Non pow2 numbers need an additional mad AFAIK and for more info on this see libdivide) I don’t think it’s malicious just a bit too much focus on performance got in the way of practicality on ARM.

**Comment by hramrach** [comment]
Linux has now boot time dynamic page size switch.

That makes page size a runtime selection, not something that is fixed, even for one OS distribution.

**Comment by eslerm** [comment]
Because jemalloc is unportable, both Fedora and Ubuntu force `--with-lg-page=16` on all ARM builds of their downstream package.

**Comment by hramrach** [comment]
Some distributions even provide multiple kernels with different page sizes. It's normal that page size changes from one boot to another.
