### ISSUE TITLE
Jemalloc Resident Memory stats goes up when others go down

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#516]
While testing memory mapping fixes with 4.2.1 I found that when we unload a bunch data and reset the arena jemalloc stats exhibit the following behavior.

We are wondering if this is a stats issue of there is a problem with a memory leak. Process private bytes seem to go down but it is hard to tell how much is the right amount.
![jeresidentup](https://cloud.githubusercontent.com/assets/11303988/20731077/8bbc8b64-b63d-11e6-9c38-80ebf6d9e901.png)

**Comment by jasone** [comment]
Here's what I think is happening (you can verify it by doing an arena purge just after the reset).  Some of the arena chunks are only partially active prior to the reset, but during the reset the chunks are marked as uniformly dirty so that they can be bulk deallocated.  Since dirty memory is incorporated in the resident stat, this artificial inflation in the dirty memory stat makes it appear as though resident memory has increased.  In fact no clean pages are dirtied during the reset.

For what it's worth, this over-estimate issue for the resident memory stat also applies to sparsely utilized page runs (whether for large objects or incompletely used small allocation runs), as well as for huge allocations.

**Comment by yuslepukhin** [comment]
@jasone Are you suggesting to purge arena right after it is reset?

**Comment by jasone** [comment]
Yes, but only as a test, or if the arena won't be used anymore after the reset.  I think this behavior is worth clarifying in the documentation.

**Comment by yuslepukhin** [comment]
@jasone after the reset we put it back in a pool of arenas for re-use before we decide call extend again. We pick the lowest available since it is initialized automatically. Is this a good practice?

**Comment by jasone** [comment]
That sounds reasonable.  Depending on how long arenas can sit in the pool of unused arenas, you may want to call the ```arena.<i>.decay``` mallctl so that dirty doesn't linger indefinitely.  This is something we will hopefully have an automatic solution for soon (see #149).

**Comment by yuslepukhin** [comment]
@jasone Would there be any concern if I keep doing purge after reset instead of decay?

**Comment by jasone** [comment]
Purge instead of decay is fine, but it's a heavier weight operation, so the overhead may be higher than you want.

**Comment by yuslepukhin** [comment]
@jasone This worked for us. So closing.

**Comment by jasone** [comment]
Re-opening, to track the need for additional documentation. ;-)

**Comment by jasone** [comment]
This isn't relevant to 5.0.0 (extents rather than chunks); closing.
