### ISSUE TITLE
MySQL with jemalloc 4.4.0 ld-preloaded has its VSZ bloating significantly

### ISSUE THREAD

**Issue by poige** [jemalloc/jemalloc#530]
Say, with RSS around 18 GB, VSZ is now around 50 GB. `pmap` claims it's writeable so in fact it terribly looks like a memory leak. More details are coming soon.

**Comment by poige** [comment]
Well, dunno what to tell more except that with tcmalloc VSZ stays just RSS + 2 GB. @jasone anything?

**Comment by jasone** [comment]
There's not enough information here to hazard any educated guesses, nor to reproduce the issue.  If you investigate further and determine that there is an issue in jemalloc, please report back with enough detail to narrow down the set of possible explanations, as well as a simple reproduction.

**Comment by jasone** [comment]
You may benefit from reading online resources on "how to report a software defect", "how to report a software bug", etc.  Your report contains only minimal information that doesn't even indicate you've thoroughly investigated, let alone providing enough information for it to be actionable.  I will not investigate an issue when presented only with vague information and no clear reproduction steps.  Nor will I typically investigate if given a report that lacks a clear indication of how/why jemalloc may be functioning incorrectly.  Only rarely will I choose to develop domain expertise (in this case for MySQL) in order to deeply investigate an issue.  Investigation takes time and effort, both of which are finite resources for me.  My role here is to make jemalloc work as well as possible across myriad use cases, and your communication suggests you are expecting me to take on a far broader role to your benefit, at non-trivial cost to me.  I will not.

**Comment by poige** [comment]
In short you've said "I don't care". Well, if you don't care than I don't
care — for sure. Tcmalloc works fine, why bothering. Closed.

**Comment by poige** [comment]
I stand corrected (by myself): ES (java) bloats with tcmalloc as well, so it's not jemalloc-only seen. But MySQL's case is clearly an opposite.
