### ISSUE TITLE
--with-jemalloc-prefix="je_" undefined symbol je_malloc

### ISSUE THREAD

**Issue by AuthorityFX** [jemalloc/jemalloc#622]
Built jemalloc with --with-jemalloc-prefix="je_" configure flag.
Dynamically linked libjemalloc.so to my shared library at build.
When my shared library is loaded into the executable at runtime I get "undefined symbol je_malloc"

If built without --with-jemalloc-prefix="je_", jemalloc links correctly at runtime — malloc_stats_print() returns normally.

Am I missing something or is this a bug with the prefixing?

**Comment by davidtgoldblatt** [comment]
Things seemed to sanity check for me after "./configure --with-jemalloc-prefix="je_custom_prefix_" ; make -j32 ; nm lib/libjemalloc.so | grep je_custom_prefix_" on both dev and 4.4.0.

Can you take a look at the symbols in the library you're producing and see what the results are?

**Comment by AuthorityFX** [comment]
I was running ../configure from jemalloc/build.  It seems you must configure and build from the root for --with-jemalloc-prefix work.

**Comment by jasone** [comment]
I tested with a separate build directory:
```
$ autoconf
$ mkdir build
$ cd build
$ ../configure --with-jemalloc-prefix=je_
$ make all tests && make check
$ nm -a lib/libjemalloc.so.2 | grep ' T '
0000000000050c3c T _fini
0000000000003600 T _init
00000000000085e0 T je_aligned_alloc
0000000000008650 T je_calloc
000000000000d400 T je_dallocx
0000000000009f10 T je_free
000000000000e990 T je_mallctl
000000000000ed80 T je_mallctlbymib
000000000000eba0 T je_mallctlnametomib
0000000000007cc0 T je_malloc
000000000000ef90 T je_malloc_stats_print
000000000000f1d0 T je_malloc_usable_size
000000000000aab0 T je_mallocx
000000000000a640 T je_memalign
000000000000e510 T je_nallocx
00000000000085d0 T je_posix_memalign
000000000000c360 T je_rallocx
0000000000008f50 T je_realloc
000000000000d1d0 T je_sallocx
000000000000dbc0 T je_sdallocx
000000000000a6a0 T je_valloc
000000000000ce30 T je_xallocx
```

All appearances are that there is something misconfigured in your environment, such as trying to use the wrong jemalloc library at run time.  If you discover otherwise, please reopen with detailed reproduction steps so we can reproduce the issue.

**Comment by danlea** [comment]
For posterity, I'd like to make it clear that this can be expected in the case that another non-prefixed (or differently prefixed) jemalloc DSO is targeted with `LD_PRELOAD` at run time. This configuration is liable to occur when a downstream user attempts to `LD_PRELOAD` a standard jemalloc in an application that includes a prefixed jemalloc _with the standard SO name_. The application vendor can avoid this scenario by ensuring that the shipped SO is suitably modified: filename _and_ SONAME ELF header field. This can be achieved with the `--with-install-suffix` configure option (the build sets the SONAME to the file name, which is suffixed).

As a rule, SO names should only match if they are API compatible: using `--with-jemalloc-prefix` _without also specifying_ `--with-install-suffix` (or otherwise modifying SO name) should probably be _precluded by the build_ (perhaps requiring a new option targeted specifically at SO name). Builders can of course fix this post-build, e.g. by renaming and patching with `patchelf --so-name`, but I think there's an awareness issue here that could, at the very least, be helped with a mention in the documentation for `--with-jemalloc-prefix`.
