### ISSUE TITLE
Optimizing free fast path by caching extent internals in rtree cache

### ISSUE THREAD

**Issue by interwq** [jemalloc/jemalloc#694]
With the new extent based design, rtree lookup is on the critical path of free, just like chunk header access in previous chunk based design. 

As getting the extent based on the pointer-to-free is the first step on free, we are expecting a fairly large chunk of overhead from it. However, currently there is a second cache access incurs even higher overhead: after getting the ptr to the extent from rtree (almost always cached lookup), we need to dereference the extent ptr, e.g. reading if it's a slab, getting binind,  https://github.com/jemalloc/jemalloc/blob/dev/include/jemalloc/internal/arena_inlines_b.h#L138

This means, we are suffering 2 sequential cache misses, first getting extent ptr, second reading extent content. With the additional overhead from the second step, the free fast path is ~30% slower in the application benchmark I had.

To make the data access more cache friendly, we should cache more stuff in rtree_ctx_cache_elm_s, e.g. e_slab and e_slab_data->binind, so that the free fast path doesn't have to dereference *extent. I believe with this caching change we should be able to speed up free significantly to match the chunk based design.

**Comment by jasone** [comment]
Let's do #461 as a preparatory step for this.  We may be able to wedge most of the flags into the rtree.

**Comment by jasone** [comment]
I have a working solution for this now (as well as the hard part of #461), in this [ephemeral branch](https://github.com/jasone/jemalloc/tree/extent_usize).  The branch needs some commit re-ordering/cleanup, and I also want to remove calls to ```iealloc()``` from more paths, so that extent pointers are less proactively looked up and passed around.  I haven't yet implemented a packed ```rtree_leaf_elm_t``` solution for 64-bit systems, but it should be possible with no changes to the rtree API.

The fast path is really sensitive to unnecessary work, so I had to create various combo rtree read/write interfaces.  Microbenchmarks show comparable before/after performance, and this presumably will make a big difference for deallocation cache miss rate.
