### ISSUE TITLE
very high metadata percentage

### ISSUE THREAD

**Issue by oranagra** [jemalloc/jemalloc#707]
it looks like after allocating a lot of large allocations (6k) and then replacing these allocations with smaller ones (50 bytes), there are some metadata inefficiencies that isn't there if you only allocate either of these separately.

attached is a small test application that reproduces it and shows some 70% of the memory used by metadata (after purging the unused pages).

[test_meta.c.txt](https://github.com/jemalloc/jemalloc/files/853334/test_meta.c.txt)
[test_meta.txt](https://github.com/jemalloc/jemalloc/files/853333/test_meta.txt)

after freeing the small allocation, it looks like the metadata is reduced, but then i notice that another purge increases the resident?

**Comment by jasone** [comment]
Thanks for providing a test program; this would have been hard to figure out otherwise.  There are two confounding factors at play:
1) The mallctl machinery allocates nearly a megabyte of metadata the first time called.
2) Purging can allow a chunk's mixture of clean and dirty runs to coalesce into a single clean run, at which point the chunk is deallocated, and due to an artifact of chunk deallocation, the entire chunk is then considered dirty (there's no way to track that only the chunk header pages are dirty).  It's debatable whether jemalloc should automatically purge twice to deal with this.

The attached test program moves all explicit allocation activity to arena 1 (dangerously; be more careful in application code), avoids tcache, and purges an additional time such that the number of reported dirty pages reaches 0: [test_meta_modified.c.txt](https://github.com/jemalloc/jemalloc/files/859795/test_meta_modified.c.txt).  If you run the program you should see arena 1 left over with only the metadata for its spare chunk.

**Comment by oranagra** [comment]
@jasone thanks for looking into it.
i'm not sure i follow you. 

1.  the 1mb of metadata used by mallctl machinery should be visible at the tester's "startup" print, so i don't consider it an overhead of allocation and deallocation. (also 1mb is not that much to waste, but 160mb **is**)

2. purging in this test application is just a mean to get a better view of the metrics, i don't mind purging twice.

3) i didn't understand why you changed to arena 1, and why you allocate with TCACHE_NONE?
i **do** understand why for this test we want to release with TCACHE_NONE: so that the allocations are truly returned to the arenas and can be released and purged. is there any other reason?

4) maybe it wasn't clear from my original post, but i didn't really care about the last stages were i free everything (what's printed below the `#####` markings), i only added that so that we can see that eventually the memory **is** released and there are no leaks.

so looking at the information printed after the 6k allocations are replaced with 50b allocations, there is some 160mb of metadata (which is 72% of the rss).
i used your modified version, but this overhead remains, even after double purging. (see output below)

if that's a jemalloc limitation, i would like to understand it's boundaries (i saw somewhere that mentions that metadata will not grow above 2%).
if there's a way to work around it, i would like to know it, although i don't think you can expect the applications (naive users) to be aware of that and solve it.

thanks a lot.

```startup
  allocated=263040, active=294912, resident=937984, metadata=905088 (96%)
  frag=12% (257% rss overhead), frag_bytes=31872 (674944 rss overhead)

populated large
  allocated=6144302208, active=6144344064, resident=6305456128, metadata=161401664 (3%)
  frag=0% (3% rss overhead), frag_bytes=41856 (161153920 rss overhead)

replaced with small
  allocated=64302208, active=64344064, resident=231641088, metadata=161401664 (70%)
  frag=0% (260% rss overhead), frag_bytes=41856 (167338880 rss overhead)

after purge
  allocated=64302208, active=64344064, resident=225456128, metadata=161401664 (72%)
  frag=0% (251% rss overhead), frag_bytes=41856 (161153920 rss overhead)

after second purge
  allocated=64302208, active=64344064, resident=225456128, metadata=161401664 (72%)
  frag=0% (251% rss overhead), frag_bytes=41856 (161153920 rss overhead)
#############################################################
#############################################################

free small
  allocated=302208, active=344064, resident=2617344, metadata=2141376 (82%)
  frag=14% (766% rss overhead), frag_bytes=41856 (2315136 rss overhead)

after purge
  allocated=302208, active=344064, resident=45117440, metadata=1023168 (2%)
  frag=14% (14829% rss overhead), frag_bytes=41856 (44815232 rss overhead)

after second purge
  allocated=302208, active=344064, resident=1077248, metadata=1023168 (95%)
  frag=14% (256% rss overhead), frag_bytes=41856 (775040 rss overhead)
```

**Comment by jasone** [comment]
Re: (3), I moved the manual allocations to arena 1 in order to completely separate concerns and simplify analysis.

Here is what's happening:
1) The large allocations consume all but one page of each of the many chunks created to contain them.
2) The small allocations consume the single remaining pages of the chunks created in (1) faster than the large allocations are replaced (64 small allocations per page run, ~500 large allocations per chunk), such that all the chunks created in (1) remain, most of them with only a single active page.

The "oldest best fit" placement algorithm prioritizes page run fit over age.  Back before chunk age was tracked we used "lowest [address] best fit", and at one point I experimented with "best lowest fit".  In retrospect, the inadequacy of "lowest" doomed those experiments, because ```mmap()```ed memory grows downward on many systems.  I just created #711 to track a repeat experiment.

Incidentally, if you modify your test program to reverse the order in which the large allocations are freed, you will see dramatically lower chunk fragmentation just after the "replace with small" step.

**Comment by oranagra** [comment]
@jasone i'm not sure i'm able to follow all the details, so let me try to sum up the bottom line (let me know if i'm right):
1) this is a problem that is caused by the way jemalloc reuses pages from one bin to serve anther.
2) you are considering changing the algorithm so that it won't happen (or at least won't be so severe)
3) although jemalloc reports that as metadata, it isn't actually metadata, but more a fragmentation issue.
4) you mentioned that if i had freed them in a different order, it wouldn't have happen, does it mean that if i'll re-allocate all the allocations that remain at the end, i may be able to defrag that "metadata" and reduce the immense overhead?

i should note that obviously i didn't come up with this pathological case just for fun, this simply happens in redis due to the LRU eviction. @antirez FYI

**Comment by jasone** [comment]
Here's a one-sentence explanation of a weakness in jemalloc 4.x and earlier: 

> A single active page run within a chunk prevents the chunk (and therefore all its header metadata) from being deallocated.

The test program perfectly exploits this weakness; at the conclusion of the "replace with small" step, all of the chunks created during the "populate large" phase remain in use, but the vast majority of them each contain only a single page of active allocations.

Re: (4), I merely mentioned reversing the large deallocation order so you could observe the effect; I don't think it's a practical strategy for reducing chunk fragmentation since you'd need to know jemalloc's memory packing comparison ordering to consistently deallocate in reverse packing order (and real world applications would have confounding layout issues due to unrelated allocations).  Unfortunately I don't have any good ideas for a reliable workaround for this problem.  Changing jemalloc to use "first" fit would make the problem go away, but at non-trivial search overhead cost that I'm not sure we can justify in general.

Did you see my comments on #712?  We don't have the chunk fragmentation problem in the dev branch (there are no chunks), so although we remain vulnerable to virtual memory fragmentation for such allocation patterns, the metadata overhead is ~10X lower unused pages -- ~0.002 versus ~0.02.  That's still not very satisfying though when looking at extreme examples like this test program.

**Comment by jasone** [comment]
We just landed #712, which should resolve the fragmentation issue starting with 5.0.0.

**Comment by oranagra** [comment]
thanks a lot.

out of curiosity, i run that test with the dev branch, and it still shows 98mb of metadata (61% after purge)
```
startup
  allocated=110656, active=122880, resident=2498560, metadata=2398656 (96%)
  frag=11% (2158% rss overhead), frag_bytes=12224 (2387904 rss overhead)

populated large
  allocated=6144120896, active=6144135168, resident=6241263616, metadata=97119552 (2%)
  frag=0% (2% rss overhead), frag_bytes=14272 (97142720 rss overhead)

replaced with small
  allocated=64120896, active=64135168, resident=6242934784, metadata=98786112 (2%)
  frag=0% (9636% rss overhead), frag_bytes=14272 (6178813888 rss overhead)

after purge
  allocated=64120896, active=64135168, resident=162930688, metadata=98786112 (61%)
  frag=0% (154% rss overhead), frag_bytes=14272 (98809792 rss overhead)

after second purge
  allocated=64120896, active=64135168, resident=162930688, metadata=98786112 (61%)
  frag=0% (154% rss overhead), frag_bytes=14272 (98809792 rss overhead)
```

**Comment by jasone** [comment]
I think there are two contributing factors to the somewhat high metadata overhead in the dev branch:
- The portions of the radix tree that were initialized during the "populate large" phase remains allocated.
- The extent structures that were used to track the large allocations are cached for future use.  #716 incrementally improves this, and we will probably implement a further size reduction.

**Comment by jasone** [comment]
We have reduced ```extent_t``` to 128 bytes on 64-bit systems as of 07f4f93434b8fca5aabedbbaa122fa8f6eb681a6.  @interwq and I have discussed various options for data structure changes that would enable further metadata savings and/or lower TLB pressure, but none of the options are clearly superior for common workloads.  We're going to gain some experience with the current implementation before we further consider alternatives.

**Comment by oranagra** [comment]
for the record, i built the latest dev branch and we still have some 80MB (56%) overhead in this case.
this is a slight improvement it used to be 161MB (72%)
```
startup
  allocated=110656, active=122880, resident=2502656, metadata=2398272 (96%)
  frag=11% (2162% rss overhead), frag_bytes=12224 (2392000 rss overhead)

populated large
  allocated=6144111680, active=6144126976, resident=6223114240, metadata=78982880 (1%)
  frag=0% (1% rss overhead), frag_bytes=15296 (79002560 rss overhead)

replaced with small
  allocated=64185408, active=64200704, resident=6224445440, metadata=80316256 (1%)
  frag=0% (9598% rss overhead), frag_bytes=15296 (6160260032 rss overhead)

after purge
  allocated=64185408, active=64200704, resident=144506880, metadata=80316256 (56%)
  frag=0% (125% rss overhead), frag_bytes=15296 (80321472 rss overhead)

```
