### ISSUE TITLE
Question: Reason for mallocx failure

### ISSUE THREAD

**Issue by 428desmo** [jemalloc/jemalloc#844]
I observe the memory allocation with mallocx() fails (returns NULL) when my server program is running under high load.  However, the free memory on the system _seems_ not exhausted -- according to general Linux commands "free", "top", "vmstat"; The memory might be exhausted, but it is not so obvious, at least.

The jemalloc manual page says:

> The mallocx() and rallocx() functions return a pointer to the allocated memory if successful; otherwise a NULL pointer is returned to indicate insufficient contiguous memory was available to service the allocation request.

Then, does the allocation-failure definitely mean there is no "contiguous memory"? Or is there any other possible factor (I don't know, but something like mutex contention)?

Can we tune/configure the size of the contiguous memory for a certain size of requested memory?

**Comment by jasone** [comment]
If ```mallocx()``` returns ```NULL```, it really does mean that jemalloc was unable to acquire sufficient contiguous memory from the kernel to satisfy the request.  There is one peculiar failure mode for Linux worth considering: the maximum number of distinct VM entries per process is 65530 (see e.g. ```sysctl vm.max_map_count```).  There was a regression in 4.2.0 (fixed by 05a9e4ac651eb0c728e83fd883425c4894a2ae2b in 4.2.1) that caused excessive VM map fragmentation.  Other causes of VM map entry exhaustion include lots of threads, guard pages, etc.

**Comment by 428desmo** [comment]
Thanks @jasone for so quick response!
I will increase `vm.max_map_count` and re-test to see if the issue would still be reproduced.

**Comment by jasone** [comment]
Feel free to re-open if you continue to hit related issues.
