### ISSUE TITLE
O_CLOEXEC on linux under 2.6.23

### ISSUE THREAD

**Issue by wangpeiwen** [jemalloc/jemalloc#946]
I notice that jemalloc now use `open` with `O_CLOEXEC` which is supported since linux 2.6.23
Can we support the old linux or not?

**Comment by davidtgoldblatt** [comment]
In general we'll be sort of vague to support levels for older kernels, since we don't test on them and can't really promise not to break them in refactorings and such.

That said, this is sufficiently local and easy to reason about that, if you don't mind submitting a pull request falling back to fcntl'ing FD_CLOEXEC when O_CLOEXEC isn't defined, I'll accept.

**Comment by zonyitoo** [comment]
It should be fixed right now. Please @davidtgoldblatt check https://github.com/jemalloc/jemalloc/pull/961 this pr. We should not call `fcntl` if `open` fails.

**Comment by davidtgoldblatt** [comment]
Resolved by #959 and #961.
