### ISSUE TITLE
Please update jemalloc/jemalloc-cmake for 5.0.1

### ISSUE THREAD

**Issue by nicolaichuk** [jemalloc/jemalloc#992]
Please update https://github.com/jemalloc/jemalloc-cmake for 5.0.1

**Comment by davidtgoldblatt** [comment]
While we're broadly at consensus that CMake is The Future, I don't want to commit to keeping those branches up to date before we actually make the switch. I'm happy to stamp pull requests that upgrade to new versions, but not much more than that.

**Comment by nicolaichuk** [comment]
> ...before we actually make the switch...

@davidtgoldblatt, who can decide to do this switch?

**Comment by mattsta** [comment]
As a reminder, jemalloc-cmake is kinda named weird because it's windows-only and pollutes the jemalloc history a lot.

I spent a few weeks refactoring jemalloc-cmake into a more workable version at https://github.com/mattsta/jemalloc/branches (not focused on windows) that should hopefully be a better starting point going forward.

But! jemalloc has started adding a lot more unix utilities and shell scripts into the autoconf build process, and that's making the CMake-ificaition slightly more tedious for multi-platform conversions as well (the auto-symbol extraction on build instead of in-source files, etc).

**Comment by davidtgoldblatt** [comment]
> who can decide to do this switch?

I guess the "who" there is the jemalloc committers. We've already decided that we want to do the switch eventually, it's just a question of timing / work involved.

> When is this change planned?

To be honest, it's not even on our roadmap for this half, which is already somewhat oversubscribed. I've sort of been hoping that the FreeBSD compiler story will change enough that we can flip the C++ switch, at which point converting becomes easier (e.g. for the custom name mangling that @mattsta mentioned, we can just put everything in an internal namespace). We're not sure of the timeline on that, either.
