### ISSUE TITLE
Questions about private heap usage and address space control

### ISSUE THREAD

**Issue by myocytebd** [jemalloc/jemalloc#995]
1. Is it possible to limit range of virtual address space?
   e.g. to ensure all allocation lives in the range of [ N, N+2^32 ). (any N)

2. What is the proper way to create a private heap (like win32 api)? arena.create?
   No API seems able to specify tcache and arena at the same time.
   In case of single-threaded usage on a manually created arena, is tcache useless?

**Comment by davidtgoldblatt** [comment]
We may have to create a bit of metadata that has to live outside the range, but otherwise, the extent hooks api can accomplish one (there are details in the man page).

I'm not familiar with the win32 API but, just from the name, arena.create sounds like what you want. It's true that this won't segregate that arena's allocations from other arena's ones. To do that, you'll have to create a tcache (also using the relevant mallctl) that you only use with that arena.

**Comment by davidtgoldblatt** [comment]
Closing for now, but feel free to reopen if you have additional questions.
